#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_full_usa_states.py
Generates comprehensive top-order newspaper directories for all 50 US States + District of Columbia.
Outputs:
- app/src/main/assets/states/{state_slug}.json (52 individual state JSONs)
- app/src/main/assets/states/all_states.json (Comprehensive master catalog)
- app/src/main/assets/usa_states_newspapers.json (Category menu index with accurate counts)
"""

import json
import os
import re

assets_dir = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "assets")
states_dir = os.path.join(assets_dir, "states")
os.makedirs(states_dir, exist_ok=True)

def favicon(domain):
    return f"https://www.google.com/s2/favicons?sz=128&domain={domain}"

# ==============================================================================
# COMPREHENSIVE CURATED TOP NEWSPAPERS BY US STATE (RANKED BY PROMINENCE & CIRCULATION)
# ==============================================================================
RAW_STATE_PAPERS = {
    "Alabama": [
        ("The Birmingham News / AL.com", "al.com", "Birmingham", "Top Daily"),
        ("Mobile Press-Register", "al.com/mobile", "Mobile", "Top Daily"),
        ("Montgomery Advertiser", "montgomeryadvertiser.com", "Montgomery", "State Capital Daily"),
        ("The Huntsville Times", "al.com/huntsville", "Huntsville", "Top Daily"),
        ("The Tuscaloosa News", "tuscaloosanews.com", "Tuscaloosa", "Daily"),
        ("The Gadsden Times", "gadsdentimes.com", "Gadsden", "Daily"),
        ("The Dothan Eagle", "dothaneagle.com", "Dothan", "Daily"),
        ("The Decatur Daily", "decaturdaily.com", "Decatur", "Daily"),
        ("The Anniston Star", "annistonstar.com", "Anniston", "Daily"),
        ("Opelika-Auburn News", "oanow.com", "Auburn", "Daily"),
        ("The TimesDaily", "timesdaily.com", "Florence", "Daily"),
        ("The Cullman Times", "cullmantimes.com", "Cullman", "Daily"),
        ("The Daily Mountain Eagle", "mountaineagle.com", "Jasper", "Daily"),
        ("The Selma Times-Journal", "selmatimesjournal.com", "Selma", "Daily"),
        ("The Sand Mountain Reporter", "sandmountainreporter.com", "Albertville", "Daily"),
        ("The Southeast Sun", "southeastsun.com", "Enterprise", "Weekly"),
        ("The St. Clair Times", "stclairtimes.com", "Pell City", "Weekly"),
        ("The Citizen of East Alabama", "thecitizenofeastalabama.com", "Phenix City", "Weekly"),
        ("Over the Mountain Journal", "otmj.com", "Vestavia Hills", "Weekly"),
        ("Shelby County Reporter", "shelbycountyreporter.com", "Columbiana", "Weekly")
    ],
    "Alaska": [
        ("Anchorage Daily News", "adn.com", "Anchorage", "State Flagship Daily"),
        ("Fairbanks Daily News-Miner", "newsminer.com", "Fairbanks", "Top Daily"),
        ("Juneau Empire", "juneauempire.com", "Juneau", "State Capital Daily"),
        ("Ketchikan Daily News", "ketchikandailynews.com", "Ketchikan", "Daily"),
        ("Peninsula Clarion", "peninsulaclarion.com", "Kenai", "Daily"),
        ("The Frontiersman", "frontiersman.com", "Wasilla", "Daily"),
        ("Kodiak Daily Mirror", "kodiakdailymirror.com", "Kodiak", "Daily"),
        ("Sitka Sentinel", "sitkasentinel.com", "Sitka", "Daily"),
        ("Homer News", "homernews.com", "Homer", "Weekly"),
        ("The Cordova Times", "thecordovatimes.com", "Cordova", "Weekly"),
        ("The Arctic Sounder", "thearcticsounder.com", "Barrow / Utqiagvik", "Regional Weekly"),
        ("The Bristol Bay Times", "thebristolbaytimes.com", "Dillingham", "Regional Weekly"),
        ("Chilkat Valley News", "chilkatvalleynews.com", "Haines", "Weekly"),
        ("Nome Nugget", "nomenugget.com", "Nome", "Oldest AK Newspaper"),
        ("Petersburg Pilot", "petersburgpilot.com", "Petersburg", "Weekly"),
        ("Wrangell Sentinel", "wrangellsentinel.com", "Wrangell", "Weekly")
    ],
    "Arizona": [
        ("The Arizona Republic", "azcentral.com", "Phoenix", "State Flagship Daily"),
        ("Arizona Daily Star", "tucson.com", "Tucson", "Top Metro Daily"),
        ("East Valley Tribune", "eastvalleytribune.com", "Mesa / Tempe / Chandler", "Regional"),
        ("Arizona Daily Sun", "azdailysun.com", "Flagstaff", "Top Daily"),
        ("The Daily Courier", "dcourier.com", "Prescott", "Daily"),
        ("Yuma Sun", "yumasun.com", "Yuma", "Daily"),
        ("Today's News-Herald", "havasunews.com", "Lake Havasu City", "Daily"),
        ("Sierra Vista Herald", "myheraldreview.com", "Sierra Vista", "Daily"),
        ("Casa Grande Dispatch", "pinalcentral.com", "Casa Grande", "Daily"),
        ("The Kingman Miner", "kdminer.com", "Kingman", "Daily"),
        ("White Mountain Independent", "wmicentral.com", "Show Low", "Semi-Weekly"),
        ("Sedona Red Rock News", "redrocknews.com", "Sedona", "Semi-Weekly"),
        ("Payson Roundup", "paysonroundup.com", "Payson", "Semi-Weekly"),
        ("Verde Independent", "verdenews.com", "Cottonwood", "Weekly"),
        ("Ahwatukee Foothills News", "ahwatukee.com", "Phoenix", "Weekly"),
        ("Scottsdale Progress", "scottsdaleprogress.com", "Scottsdale", "Weekly"),
        ("Navajo Times", "navajotimes.com", "Window Rock", "Official Tribal Weekly"),
        ("Green Valley News", "gvnews.com", "Green Valley", "Semi-Weekly")
    ],
    "Arkansas": [
        ("Arkansas Democrat-Gazette", "arkansasonline.com", "Little Rock", "State Flagship Daily"),
        ("Northwest Arkansas Democrat-Gazette", "nwaonline.com", "Fayetteville", "Top Metro Daily"),
        ("Southwest Times Record", "swtimes.com", "Fort Smith", "Top Daily"),
        ("The Jonesboro Sun", "jonesborosun.com", "Jonesboro", "Top Daily"),
        ("The Sentinel-Record", "hotsr.com", "Hot Springs", "Daily"),
        ("Pine Bluff Commercial", "pbcommercial.com", "Pine Bluff", "Daily"),
        ("The Baxter Bulletin", "baxterbulletin.com", "Mountain Home", "Daily"),
        ("El Dorado News-Times", "eldoradonews.com", "El Dorado", "Daily"),
        ("Benton Courier", "bentoncourier.com", "Benton", "Daily"),
        ("The Cabin / Log Cabin Democrat", "thecabin.net", "Conway", "Daily"),
        ("Harrison Daily Times", "harrisondaily.com", "Harrison", "Daily"),
        ("Russellville Courier", "couriernews.com", "Russellville", "Daily"),
        ("Paragould Daily Press", "paragoulddailypress.com", "Paragould", "Daily"),
        ("The Daily Citizen", "thedailycitizen.com", "Searcy", "Daily"),
        ("Batesville Guard", "guardonline.com", "Batesville", "Daily"),
        ("Texarkana Gazette", "texarkanagazette.com", "Texarkana", "Daily")
    ],
    "California": [
        ("Los Angeles Times", "latimes.com", "Los Angeles", "Top National & State Daily"),
        ("San Francisco Chronicle", "sfchronicle.com", "San Francisco", "Bay Area Flagship Daily"),
        ("The San Diego Union-Tribune", "sandiegouniontribune.com", "San Diego", "Top Metro Daily"),
        ("The Sacramento Bee", "sacbee.com", "Sacramento", "State Capital Flagship Daily"),
        ("The Mercury News", "mercurynews.com", "San Jose", "Silicon Valley Flagship Daily"),
        ("Orange County Register", "ocregister.com", "Anaheim / Santa Ana", "Top Metro Daily"),
        ("The Fresno Bee", "fresnobee.com", "Fresno", "Central Valley Daily"),
        ("The Press-Enterprise", "pe.com", "Riverside / San Bernardino", "Inland Empire Daily"),
        ("East Bay Times", "eastbaytimes.com", "Oakland", "East Bay Daily"),
        ("The Bakersfield Californian", "bakersfield.com", "Bakersfield", "Daily"),
        ("The Modesto Bee", "modbee.com", "Modesto", "Daily"),
        ("The Press Democrat", "pressdemocrat.com", "Santa Rosa", "North Bay Daily"),
        ("The Tribune", "sanluisobispo.com", "San Luis Obispo", "Central Coast Daily"),
        ("Santa Barbara News-Press", "newspress.com", "Santa Barbara", "Daily"),
        ("Ventura County Star", "vcstar.com", "Ventura", "Daily"),
        ("The Desert Sun", "desertsun.com", "Palm Springs", "Daily"),
        ("Stockton Record", "recordnet.com", "Stockton", "Daily"),
        ("The Monterey County Herald", "montereyherald.com", "Monterey", "Daily"),
        ("Santa Cruz Sentinel", "santacruzsentinel.com", "Santa Cruz", "Daily"),
        ("Chico Enterprise-Record", "chicoer.com", "Chico", "Daily"),
        ("Redding Record Searchlight", "redding.com", "Redding", "Daily"),
        ("Times-Standard", "times-standard.com", "Eureka", "Daily"),
        ("Marin Independent Journal", "marinij.com", "San Rafael", "Daily"),
        ("San Francisco Examiner", "sfexaminer.com", "San Francisco", "Daily"),
        ("Daily Breeze", "dailybreeze.com", "Torrance / South Bay", "Daily"),
        ("Long Beach Press-Telegram", "presstelegram.com", "Long Beach", "Daily"),
        ("Pasadena Star-News", "pasadenastarnews.com", "Pasadena", "Daily"),
        ("San Gabriel Valley Tribune", "sgvtribune.com", "West Covina", "Daily"),
        ("Whittier Daily News", "whittierdailynews.com", "Whittier", "Daily"),
        ("Inland Valley Daily Bulletin", "dailybulletin.com", "Ontario / Rancho Cucamonga", "Daily"),
        ("San Bernardino Sun", "sbsun.com", "San Bernardino", "Daily"),
        ("Redlands Daily Facts", "redlandsdailyfacts.com", "Redlands", "Daily"),
        ("The Daily News of Los Angeles", "dailynews.com", "Woodland Hills / LA", "Daily"),
        ("Napa Valley Register", "napavalleyregister.com", "Napa", "Daily"),
        ("Vacaville Reporter", "thereporter.com", "Vacaville", "Daily"),
        ("Daily Republic", "dailyrepublic.com", "Fairfield", "Daily"),
        ("Vallejo Times-Herald", "timesheraldonline.com", "Vallejo", "Daily"),
        ("Lodi News-Sentinel", "lodinews.com", "Lodi", "Daily"),
        ("Merced Sun-Star", "mercedsunstar.com", "Merced", "Daily"),
        ("Visalia Times-Delta", "visaliatimesdelta.com", "Visalia", "Daily"),
        ("Hanford Sentinel", "hanfordsentinel.com", "Hanford", "Daily"),
        ("Porterville Recorder", "recorderonline.com", "Porterville", "Daily"),
        ("The Daily Independent", "ridgecrestca.com", "Ridgecrest", "Daily"),
        ("Antelope Valley Press", "avpress.com", "Palmdale", "Daily"),
        ("Imperial Valley Press", "ivpressonline.com", "El Centro", "Daily"),
        ("Santa Maria Times", "santamariatimes.com", "Santa Maria", "Daily"),
        ("Lompoc Record", "lompocrecord.com", "Lompoc", "Daily"),
        ("Paso Robles Press", "pasoroblespress.com", "Paso Robles", "Weekly"),
        ("The Union", "theunion.com", "Grass Valley", "Daily"),
        ("Sierra Sun", "sierrasun.com", "Truckee / Lake Tahoe", "Weekly"),
        ("Tahoe Daily Tribune", "tahoedailytribune.com", "South Lake Tahoe", "Weekly"),
        ("Auburn Journal", "goldcountrymedia.com", "Auburn", "Weekly"),
        ("The Davis Enterprise", "davisenterprise.com", "Davis", "Semi-Weekly"),
        ("Daily Democrat", "dailydemocrat.com", "Woodland", "Daily"),
        ("Appeal-Democrat", "appeal-democrat.com", "Marysville", "Daily"),
        ("Colusa County Sun-Herald", "appealdemocrat.com/colusa_sun_herald", "Colusa", "Weekly"),
        ("Ukiah Daily Journal", "ukiahdailyjournal.com", "Ukiah", "Daily"),
        ("The Willits News", "willitsnews.com", "Willits", "Weekly"),
        ("Fort Bragg Advocate-News", "advocate-news.com", "Fort Bragg", "Weekly"),
        ("Mendocino Beacon", "mendocinobeacon.com", "Mendocino", "Weekly"),
        ("Lake County Record-Bee", "record-bee.com", "Lakeport", "Daily"),
        ("Red Bluff Daily News", "redbluffdailynews.com", "Red Bluff", "Daily"),
        ("Corning Observer", "corningobserver.com", "Corning", "Weekly"),
        ("Mount Shasta Herald", "mtshastanews.com", "Mount Shasta", "Weekly"),
        ("Siskiyou Daily News", "siskiyoudaily.com", "Yreka", "Weekly")
    ],
    "Colorado": [
        ("The Denver Post", "denverpost.com", "Denver", "State Flagship Daily"),
        ("The Gazette", "gazette.com", "Colorado Springs", "Top Metro Daily"),
        ("Daily Camera", "dailycamera.com", "Boulder", "Top University Daily"),
        ("The Coloradoan", "coloradoan.com", "Fort Collins", "Top Daily"),
        ("The Daily Sentinel", "gjsentinel.com", "Grand Junction", "Western Slope Flagship"),
        ("The Pueblo Chieftain", "chieftain.com", "Pueblo", "Top Southern CO Daily"),
        ("Greeley Tribune", "greeleytribune.com", "Greeley", "Top Daily"),
        ("Longmont Times-Call", "timescall.com", "Longmont", "Daily"),
        ("Loveland Reporter-Herald", "reporterherald.com", "Loveland", "Daily"),
        ("The Durango Herald", "durangoherald.com", "Durango", "Four Corners Daily"),
        ("Aspen Daily News", "aspendailynews.com", "Aspen", "Daily"),
        ("The Aspen Times", "aspentimes.com", "Aspen", "Daily"),
        ("Vail Daily", "vaildaily.com", "Vail", "Daily"),
        ("Steamboat Pilot & Today", "steamboatpilot.com", "Steamboat Springs", "Daily"),
        ("Summit Daily News", "summitdaily.com", "Frisco / Breckenridge", "Daily"),
        ("Glenwood Springs Post Independent", "postindependent.com", "Glenwood Springs", "Daily"),
        ("Montrose Daily Press", "montrosepress.com", "Montrose", "Daily"),
        ("Canon City Daily Record", "canoncitydailyrecord.com", "Canon City", "Daily"),
        ("Sterling Journal-Advocate", "journal-advocate.com", "Sterling", "Daily"),
        ("Fort Morgan Times", "fortmorgantimes.com", "Fort Morgan", "Daily"),
        ("Alamosa Citizen", "alamosacitizen.com", "Alamosa", "San Luis Valley"),
        ("Telluride Daily Planet", "telluridenews.com", "Telluride", "Weekly")
    ],
    "Connecticut": [
        ("Hartford Courant", "courant.com", "Hartford", "Oldest Continuously Published US Daily"),
        ("New Haven Register", "nhregister.com", "New Haven", "Top Metro Daily"),
        ("Connecticut Post", "ctpost.com", "Bridgeport", "Gold Coast Flagship Daily"),
        ("The Day", "theday.com", "New London", "Eastern CT Daily"),
        ("Republican-American", "rep-am.com", "Waterbury", "Top Daily"),
        ("The Hour", "thehour.com", "Norwalk", "Daily"),
        ("The News-Times", "newstimes.com", "Danbury", "Daily"),
        ("Stamford Advocate", "stamfordadvocate.com", "Stamford", "Daily"),
        ("Greenwich Time", "greenwichtime.com", "Greenwich", "Daily"),
        ("Record-Journal", "myrecordjournal.com", "Meriden", "Daily"),
        ("The Middletown Press", "middletownpress.com", "Middletown", "Daily"),
        ("The Register Citizen", "registercitizen.com", "Torrington", "Daily"),
        ("Journal Inquirer", "journalinquirer.com", "Manchester", "Daily"),
        ("The Chronicle", "thechronicle.com", "Willimantic", "Daily"),
        ("The Darien Times", "darientimes.com", "Darien", "Weekly"),
        ("The Ridgefield Press", "theridgefieldpress.com", "Ridgefield", "Weekly"),
        ("New Canaan Advertiser", "ncadvertiser.com", "New Canaan", "Weekly"),
        ("Wilton Bulletin", "wiltonbulletin.com", "Wilton", "Weekly")
    ],
    "Delaware": [
        ("The News Journal", "delawareonline.com", "Wilmington", "State Flagship Daily"),
        ("Delaware State News", "delawarestatenews.net", "Dover", "State Capital Daily"),
        ("Cape Gazette", "capegazette.com", "Lewes / Rehoboth Beach", "Top Coastal Weekly"),
        ("Coastal Point", "coastalpoint.com", "Ocean View / Bethany", "Weekly"),
        ("Milford Chronicle", "milfordchronicle.net", "Milford", "Weekly"),
        ("Smyrna/Clayton Sun-Times", "scsuntimes.com", "Smyrna", "Weekly"),
        ("Harrington Journal", "harringtonjournal.com", "Harrington", "Weekly"),
        ("Sussex Countian", "sussexcountian.com", "Georgetown", "Weekly"),
        ("Newark Post", "newarkpostonline.com", "Newark", "Weekly")
    ],
    "District of Columbia": [
        ("The Washington Post", "washingtonpost.com", "Washington D.C.", "National & Capital Flagship"),
        ("The Washington Times", "washingtontimes.com", "Washington D.C.", "Leading Conservative Daily"),
        ("Politico", "politico.com", "Washington D.C.", "Premier Political News"),
        ("The Hill", "thehill.com", "Washington D.C.", "Capitol Hill Daily"),
        ("Roll Call", "rollcall.com", "Washington D.C.", "Congress & Policy Daily"),
        ("Washington Examiner", "washingtonexaminer.com", "Washington D.C.", "National Daily"),
        ("DCist / WAMU", "dcist.com", "Washington D.C.", "Local Metro News"),
        ("Washington City Paper", "washingtoncitypaper.com", "Washington D.C.", "Alternative Weekly"),
        ("The Georgetowner", "georgetowner.com", "Georgetown / D.C.", "Bi-Weekly Community"),
        ("The Washington Informer", "washingtoninformer.com", "Washington D.C.", "African-American Community Weekly"),
        ("Metro Weekly", "metroweekly.com", "Washington D.C.", "LGBTQ+ Magazine & Weekly")
    ],
    "Florida": [
        ("Tampa Bay Times", "tampabay.com", "Tampa / St. Petersburg", "Pulitzer Prize Winning Flagship"),
        ("Miami Herald", "miamiherald.com", "Miami", "South Florida Flagship Daily"),
        ("Orlando Sentinel", "orlandosentinel.com", "Orlando", "Central Florida Flagship Daily"),
        ("South Florida Sun-Sentinel", "sun-sentinel.com", "Fort Lauderdale", "Top Metro Daily"),
        ("The Florida Times-Union", "jacksonville.com", "Jacksonville", "First Coast Flagship Daily"),
        ("The Palm Beach Post", "palmbeachpost.com", "West Palm Beach", "Top Metro Daily"),
        ("Sarasota Herald-Tribune", "heraldtribune.com", "Sarasota", "Top Gulf Coast Daily"),
        ("Naples Daily News", "naplesnews.com", "Naples", "Southwest Florida Daily"),
        ("The News-Press", "news-press.com", "Fort Myers", "Top Daily"),
        ("Pensacola News Journal", "pnj.com", "Pensacola", "Panhandle Flagship Daily"),
        ("Tallahassee Democrat", "tallahassee.com", "Tallahassee", "State Capital Flagship"),
        ("The Daytona Beach News-Journal", "news-journalonline.com", "Daytona Beach", "Daily"),
        ("The Gainesville Sun", "gainesville.com", "Gainesville", "University of Florida Daily"),
        ("The Ledger", "theledger.com", "Lakeland", "Polk County Daily"),
        ("Ocala Star-Banner", "ocala.com", "Ocala", "Daily"),
        ("Florida Today", "floridatoday.com", "Melbourne / Space Coast", "Space Coast Daily"),
        ("Treasure Coast Newspapers / TCPalm", "tcpalm.com", "Stuart / Vero Beach", "Treasure Coast Daily"),
        ("Northwest Florida Daily News", "nwfdailynews.com", "Fort Walton Beach", "Panhandle Daily"),
        ("The St. Augustine Record", "staugustine.com", "St. Augustine", "Daily"),
        ("Bradenton Herald", "bradenton.com", "Bradenton", "Daily"),
        ("The Villages Daily Sun", "thevillagesdailysun.com", "The Villages", "High-Circulation Daily"),
        ("The Citizen / Key West Citizen", "keysnews.com", "Key West", "Florida Keys Daily"),
        ("Panama City News Herald", "newsherald.com", "Panama City", "Daily"),
        ("The Daily Commercial", "dailycommercial.com", "Leesburg", "Daily"),
        ("Citrus County Chronicle", "chronicleonline.com", "Crystal River", "Daily"),
        ("Hernando Sun", "hernandosun.com", "Brooksville", "Weekly"),
        ("Boca Raton Tribune", "bocaratontribune.com", "Boca Raton", "Weekly"),
        ("Miami New Times", "miaminewtimes.com", "Miami", "Alternative Weekly")
    ],
    "Georgia": [
        ("The Atlanta Journal-Constitution", "ajc.com", "Atlanta", "State Flagship Daily"),
        ("The Augusta Chronicle", "augustachronicle.com", "Augusta", "Oldest GA Newspaper"),
        ("Savannah Morning News", "savannahnow.com", "Savannah", "Coastal GA Flagship Daily"),
        ("The Telegraph", "macon.com", "Macon", "Central Georgia Daily"),
        ("Columbus Ledger-Enquirer", "ledger-enquirer.com", "Columbus", "Daily"),
        ("Athens Banner-Herald", "onlineathens.com", "Athens", "UGA Daily"),
        ("The Brunswick News", "thebrunswicknews.com", "Brunswick", "Golden Isles Daily"),
        ("Rome News-Tribune", "northwestgeorgianews.com", "Rome", "Daily"),
        ("The Valdosta Daily Times", "valdostadailytimes.com", "Valdosta", "Daily"),
        ("The Albany Herald", "albanyherald.com", "Albany", "Southwest GA Daily"),
        ("The Times", "gainesvilletimes.com", "Gainesville", "North GA Daily"),
        ("Marietta Daily Journal", "mdjonline.com", "Marietta", "Cobb County Daily"),
        ("Gwinnett Daily Post", "gwinnettdailypost.com", "Lawrenceville", "Metro Atlanta Daily"),
        ("The Daily Citizen", "daltondailycitizen.com", "Dalton", "Daily"),
        ("The Newnan Times-Herald", "times-herald.com", "Newnan", "Daily"),
        ("Statesboro Herald", "statesboroherald.com", "Statesboro", "Daily"),
        ("Thomasville Times-Enterprise", "timesenterprise.com", "Thomasville", "Daily"),
        ("The Moultrie Observer", "moultrieobserver.com", "Moultrie", "Daily"),
        ("Tifton Gazette", "tiftongazette.com", "Tifton", "Daily"),
        ("Cherokee Tribune & Ledger-News", "tribuneledgernews.com", "Canton", "Daily")
    ],
    "Hawaii": [
        ("Honolulu Star-Advertiser", "staradvertiser.com", "Honolulu", "State Flagship Daily"),
        ("The Maui News", "mauinews.com", "Wailuku / Maui", "Maui County Daily"),
        ("Hawaii Tribune-Herald", "hawaiitribune-herald.com", "Hilo", "Big Island East Daily"),
        ("West Hawaii Today", "westhawaiitoday.com", "Kailua-Kona", "Big Island West Daily"),
        ("The Garden Island", "thegardenisland.com", "Lihue / Kauai", "Kauai County Daily"),
        ("Civil Beat", "civilbeat.org", "Honolulu", "Investigative Daily"),
        ("MidWeek", "midweek.com", "Oahu", "Weekly Magazine"),
        ("Ka Leo O Hawaii", "kaleo.org", "Manoa", "University of Hawaii"),
        ("Molokai Dispatch", "themolokaidispatch.com", "Kaunakakai", "Weekly"),
        ("Lahaina News", "lahainanews.com", "Lahaina", "Maui Weekly")
    ],
    "Idaho": [
        ("Idaho Statesman", "idahostatesman.com", "Boise", "State Flagship Daily"),
        ("Idaho Press", "idahopress.com", "Nampa / Boise", "Treasure Valley Daily"),
        ("The Idaho State Journal", "journalnet.com", "Pocatello", "Eastern Idaho Daily"),
        ("Post Register", "postregister.com", "Idaho Falls", "Top Eastern ID Daily"),
        ("The Lewiston Tribune", "lmtribune.com", "Lewiston", "North Central ID Daily"),
        ("Coeur d'Alene Press", "cdapress.com", "Coeur d'Alene", "North Idaho Daily"),
        ("Times-News", "magicvalley.com", "Twin Falls", "Magic Valley Daily"),
        ("Moscow-Pullman Daily News", "dnews.com", "Moscow", "University of Idaho Daily"),
        ("Bonner County Daily Bee", "bonnercountydailybee.com", "Sandpoint", "Daily"),
        ("Idaho County Free Press", "idahocountyfreepress.com", "Grangeville", "Weekly"),
        ("Teton Valley News", "tetonvalleynews.net", "Driggs", "Weekly"),
        ("Mountain Home News", "mountainhomenews.com", "Mountain Home", "Weekly")
    ],
    "Illinois": [
        ("Chicago Tribune", "chicagotribune.com", "Chicago", "Midwest Flagship Daily"),
        ("Chicago Sun-Times", "chicago.suntimes.com", "Chicago", "Pulitzer Prize Winning Metro Daily"),
        ("Daily Herald", "dailyherald.com", "Arlington Heights / Suburban Chicago", "Major Suburban Daily"),
        ("The State Journal-Register", "sj-r.com", "Springfield", "State Capital Flagship Daily"),
        ("Journal Star", "pjstar.com", "Peoria", "Central Illinois Daily"),
        ("The News-Gazette", "news-gazette.com", "Champaign-Urbana", "Illini Flagship Daily"),
        ("Rockford Register Star", "rrstar.com", "Rockford", "Northern IL Daily"),
        ("The Herald-News", "shawlocal.com/the-herald-news", "Joliet", "Will County Daily"),
        ("The Pantagraph", "pantagraph.com", "Bloomington-Normal", "Central IL Daily"),
        ("The Southern Illinoisan", "thesouthern.com", "Carbondale", "Southern IL Daily"),
        ("Belleville News-Democrat", "bnd.com", "Belleville / Metro East", "Daily"),
        ("The Daily Southtown", "chicagotribune.com/suburbs/daily-southtown", "Tinley Park", "Daily"),
        ("Naperville Sun", "chicagotribune.com/suburbs/naperville-sun", "Naperville", "Daily"),
        ("Beacon-News", "chicagotribune.com/suburbs/aurora-beacon-news", "Aurora", "Daily"),
        ("The Courier-News", "chicagotribune.com/suburbs/elgin-courier-news", "Elgin", "Daily"),
        ("Lake County News-Sun", "chicagotribune.com/suburbs/lake-county-news-sun", "Waukegan", "Daily"),
        ("The Telegraph", "thetelegraph.com", "Alton", "Daily"),
        ("The Dispatch / The Rock Island Argus", "qconline.com", "Moline / Rock Island", "Quad Cities Daily"),
        ("Decatur Herald & Review", "herald-review.com", "Decatur", "Daily"),
        ("The Commercial-News", "commercial-news.com", "Danville", "Daily"),
        ("The Daily Chronicle", "shawlocal.com/daily-chronicle", "DeKalb", "Daily"),
        ("Northwest Herald", "shawlocal.com/northwest-herald", "Crystal Lake", "Daily"),
        ("Kankakee Daily Journal", "daily-journal.com", "Kankakee", "Daily"),
        ("The Times", "shawlocal.com/mywebtimes", "Ottawa", "Daily"),
        ("Daily Republican-Register", "republican-register.com", "Mount Carmel", "Daily")
    ],
    "Indiana": [
        ("The Indianapolis Star", "indystar.com", "Indianapolis", "State Flagship Daily"),
        ("South Bend Tribune", "southbendtribune.com", "South Bend", "Notre Dame Region Daily"),
        ("The Journal Gazette", "journalgazette.net", "Fort Wayne", "Northeast Indiana Daily"),
        ("The News-Sentinel", "news-sentinel.com", "Fort Wayne", "Fort Wayne News"),
        ("The Times of Northwest Indiana", "nwitimes.com", "Munster / Crown Point", "Chicagoland IN Daily"),
        ("Evansville Courier & Press", "courierpress.com", "Evansville", "Southern Indiana Daily"),
        ("The Herald-Times", "heraldtimesonline.com", "Bloomington", "IU Bloomington Daily"),
        ("Journal & Courier", "jconline.com", "Lafayette", "Purdue Region Daily"),
        ("The Tribune-Star", "tribstar.com", "Terre Haute", "Wabash Valley Daily"),
        ("The Herald-Bulletin", "heraldbulletin.com", "Anderson", "Daily"),
        ("Kokomo Tribune", "kokomotribune.com", "Kokomo", "Daily"),
        ("The Star Press", "thestarpress.com", "Muncie", "Ball State Region Daily"),
        ("The Elkhart Truth", "elkharttruth.com", "Elkhart", "Daily"),
        ("The Republic", "therepublic.com", "Columbus", "Daily"),
        ("Chronicle-Tribune", "chronicle-tribune.com", "Marion", "Daily"),
        ("The News-Tribune", "newsandtribune.com", "Jeffersonville / New Albany", "Daily"),
        ("Richmond Palladium-Item", "pal-item.com", "Richmond", "Daily"),
        ("Pharos-Tribune", "pharostribune.com", "Logansport", "Daily"),
        ("The Goshen News", "goshennews.com", "Goshen", "Daily"),
        ("The Herald", "duboiscountyfreepress.com", "Jasper", "Daily")
    ],
    "Iowa": [
        ("The Des Moines Register", "desmoinesregister.com", "Des Moines", "State Flagship Daily"),
        ("The Gazette", "thegazette.com", "Cedar Rapids / Iowa City", "Eastern Iowa Daily"),
        ("Quad-City Times", "qctimes.com", "Davenport", "Quad Cities Daily"),
        ("Sioux City Journal", "siouxcityjournal.com", "Sioux City", "Western Iowa Daily"),
        ("Waterloo-Cedar Falls Courier", "wcfcourier.com", "Waterloo", "Northeast Iowa Daily"),
        ("Globe Gazette", "globegazette.com", "Mason City", "North Iowa Daily"),
        ("The Daily Nonpareil", "nonpareilonline.com", "Council Bluffs", "Omaha Metro Daily"),
        ("Ames Tribune", "amestrib.com", "Ames", "Iowa State University Daily"),
        ("The Hawk Eye", "thehawkeye.com", "Burlington", "Oldest IA Daily"),
        ("The Daily Iowan", "dailyiowan.com", "Iowa City", "University of Iowa Daily"),
        ("Times-Republican", "timesrepublican.com", "Marshalltown", "Daily"),
        ("The Messenger", "messengernews.net", "Fort Dodge", "Daily"),
        ("Clinton Herald", "clintonherald.com", "Clinton", "Daily"),
        ("Muscatine Journal", "muscatinejournal.com", "Muscatine", "Daily"),
        ("Ottumwa Courier", "ottumwacourier.com", "Ottumwa", "Daily"),
        ("Newton Daily News", "newtondailynews.com", "Newton", "Daily")
    ],
    "Kansas": [
        ("The Wichita Eagle", "kansas.com", "Wichita", "State Flagship Daily"),
        ("The Topeka Capital-Journal", "cjonline.com", "Topeka", "State Capital Daily"),
        ("The Kansas City Kansan", "kansascitykansan.com", "Kansas City", "Daily"),
        ("Lawrence Journal-World", "ljworld.com", "Lawrence", "University of Kansas Daily"),
        ("The Salina Journal", "salina.com", "Salina", "Central Kansas Daily"),
        ("The Hutchinson News", "hutchnews.com", "Hutchinson", "Daily"),
        ("Manhattan Mercury", "themercury.com", "Manhattan", "Kansas State University Daily"),
        ("The Garden City Telegram", "gctelegram.com", "Garden City", "Southwest KS Daily"),
        ("The Hays Daily News", "hdnews.net", "Hays", "Northwest KS Daily"),
        ("Dodge City Daily Globe", "dodgeglobe.com", "Dodge City", "Daily"),
        ("The Morning Sun", "morningsun.net", "Pittsburg", "Daily"),
        ("Great Bend Tribune", "gbtribune.com", "Great Bend", "Daily"),
        ("Leavenworth Times", "leavenworthtimes.com", "Leavenworth", "Daily"),
        ("Ottawa Herald", "ottawaherald.com", "Ottawa", "Daily"),
        ("Arkansas City Traveler", "arkcity.net", "Arkansas City", "Daily")
    ],
    "Kentucky": [
        ("The Courier-Journal", "courier-journal.com", "Louisville", "State Flagship Daily"),
        ("Lexington Herald-Leader", "kentucky.com", "Lexington", "Bluegrass Region Flagship"),
        ("The Kentucky Enquirer", "cincinnati.com/northern-kentucky", "Covington", "Northern KY Daily"),
        ("Bowling Green Daily News", "bgdailynews.com", "Bowling Green", "South Central KY Daily"),
        ("The Paducah Sun", "paducahsun.com", "Paducah", "Western KY Daily"),
        ("Messenger-Inquirer", "messenger-inquirer.com", "Owensboro", "Western KY Daily"),
        ("The State Journal", "state-journal.com", "Frankfort", "State Capital Daily"),
        ("The Daily Independent", "dailyindependent.com", "Ashland", "Eastern KY Daily"),
        ("The News-Enterprise", "thenewsenterprise.com", "Elizabethtown", "Central KY Daily"),
        ("Richmond Register", "richmondregister.com", "Richmond", "Daily"),
        ("The Gleaner", "thegleaner.com", "Henderson", "Daily"),
        ("The Commonwealth-Journal", "somerset-kentucky.com", "Somerset", "Daily"),
        ("The Advocate-Messenger", "amnews.com", "Danville", "Daily"),
        ("Kentucky New Era", "kentuckynewera.com", "Hopkinsville", "Daily"),
        ("The Winchester Sun", "winchestersun.com", "Winchester", "Daily"),
        ("The Ledger Independent", "maysville-online.com", "Maysville", "Daily")
    ],
    "Louisiana": [
        ("The Advocate", "theadvocate.com", "Baton Rouge", "State Capital Flagship Daily"),
        ("The Times-Picayune", "nola.com", "New Orleans", "New Orleans Flagship Daily"),
        ("The Daily Advertiser", "theadvertiser.com", "Lafayette", "Acadiana Region Flagship"),
        ("The Times", "shreveporttimes.com", "Shreveport", "North Louisiana Daily"),
        ("American Press", "americanpress.com", "Lake Charles", "Southwest LA Daily"),
        ("The Town Talk", "thetowntalk.com", "Alexandria", "Central Louisiana Daily"),
        ("The News-Star", "thenewsstar.com", "Monroe", "Northeast LA Daily"),
        ("The Courier", "houmatoday.com", "Houma", "Bayou Region Daily"),
        ("Daily Comet", "dailycomet.com", "Thibodaux", "Bayou Region Daily"),
        ("The Daily World", "dailyworld.com", "Opelousas", "Daily"),
        ("St. Tammany Farmer", "theadvocate.com/st_tammany", "Covington / Northshore", "Weekly"),
        ("The Daily Review", "daily-review.com", "Morgan City", "Daily"),
        ("The Daily Iberian", "iberianet.com", "New Iberia", "Daily"),
        ("Bogalusa Daily News", "bogalusanews.com", "Bogalusa", "Daily"),
        ("Minden Press-Herald", "press-herald.com", "Minden", "Daily")
    ],
    "Maine": [
        ("Portland Press Herald", "pressherald.com", "Portland", "State Flagship Daily"),
        ("Bangor Daily News", "bangordailynews.com", "Bangor", "Top Northern ME Daily"),
        ("Sun Journal", "sunjournal.com", "Lewiston-Auburn", "Central Maine Daily"),
        ("Kennebec Journal", "centralmaine.com/kennebec-journal", "Augusta", "State Capital Daily"),
        ("Morning Sentinel", "centralmaine.com/morning-sentinel", "Waterville", "Central ME Daily"),
        ("Journal Tribune", "journaltribune.com", "Biddeford", "York County"),
        ("The Times Record", "timesrecord.com", "Brunswick", "Midcoast Daily"),
        ("The Ellsworth American", "ellsworthamerican.com", "Ellsworth", "Weekly"),
        ("Mount Desert Islander", "mdislander.com", "Bar Harbor", "Weekly"),
        ("The Forecaster", "pressherald.com/theforecaster", "Greater Portland", "Weekly Community"),
        ("Courier-Gazette", "knox.villagesoup.com", "Rockland", "Weekly"),
        ("Boothbay Register", "boothbayregister.com", "Boothbay Harbor", "Weekly"),
        ("The Lincoln County News", "lcnme.com", "Damariscotta", "Weekly")
    ],
    "Maryland": [
        ("The Baltimore Sun", "baltimoresun.com", "Baltimore", "State Flagship Daily"),
        ("The Capital", "capitalgazette.com", "Annapolis", "State Capital Flagship"),
        ("The Herald-Mail", "heraldmailmedia.com", "Hagerstown", "Western Maryland Daily"),
        ("The Daily Times", "delmarvanow.com", "Salisbury", "Eastern Shore Daily"),
        ("Cumberland Times-News", "times-news.com", "Cumberland", "Allegany County Daily"),
        ("The Frederick News-Post", "fredericknewspost.com", "Frederick", "Central MD Daily"),
        ("Carroll County Times", "carrollcountytimes.com", "Westminster", "Daily"),
        ("The Star Democrat", "stardem.com", "Easton", "Eastern Shore Daily"),
        ("Maryland Independent", "somdnews.com", "Waldorf", "Southern MD"),
        ("The Enterprise", "somdnews.com", "Lexington Park", "St. Mary's County"),
        ("The Calvert Recorder", "somdnews.com", "Prince Frederick", "Calvert County"),
        ("Baltimore City Paper", "baltimoresun.com/citypaper", "Baltimore", "Alternative Weekly"),
        ("Bethesda Magazine / Bethesda Beat", "moco360.media", "Bethesda", "Montgomery County Daily")
    ],
    "Massachusetts": [
        ("The Boston Globe", "bostonglobe.com", "Boston", "New England Flagship Daily"),
        ("Boston Herald", "bostonherald.com", "Boston", "Top Metro Daily"),
        ("Telegram & Gazette", "telegram.com", "Worcester", "Central MA Flagship Daily"),
        ("The Republican", "masslive.com", "Springfield", "Western MA Flagship Daily"),
        ("The Patriot Ledger", "patriotledger.com", "Quincy / South Shore", "Top Daily"),
        ("The Enterprise", "enterprisenews.com", "Brockton", "Daily"),
        ("The Berkshire Eagle", "berkshireeagle.com", "Pittsfield", "Berkshires Flagship Daily"),
        ("Cape Cod Times", "capecodtimes.com", "Hyannis / Cape Cod", "Cape & Islands Daily"),
        ("The Sun", "lowellsun.com", "Lowell", "Merrimack Valley Daily"),
        ("The Eagle-Tribune", "eagletribune.com", "North Andover / Lawrence", "Daily"),
        ("Daily Hampshire Gazette", "gazettenet.com", "Northampton", "Pioneer Valley Daily"),
        ("The Daily News of Newburyport", "newburyportnews.com", "Newburyport", "Daily"),
        ("The Salem News", "salemnews.com", "Salem", "North Shore Daily"),
        ("Gloucester Daily Times", "gloucestertimes.com", "Gloucester", "Cape Ann Daily"),
        ("The MetroWest Daily News", "metrowestdailynews.com", "Framingham", "Daily"),
        ("Milford Daily News", "milforddailynews.com", "Milford", "Daily"),
        ("The Standard-Times", "southcoasttoday.com", "New Bedford", "South Coast Daily"),
        ("The Herald News", "heraldnews.com", "Fall River", "Daily"),
        ("The Sun Chronicle", "thesunchronicle.com", "Attleboro", "Daily"),
        ("Taunton Daily Gazette", "tauntongazette.com", "Taunton", "Daily"),
        ("Sentinel & Enterprise", "sentinelandenterprise.com", "Fitchburg", "Daily"),
        ("The Recorder", "recorder.com", "Greenfield", "Franklin County Daily"),
        ("The Inquirer and Mirror", "ack.net", "Nantucket", "Island Weekly"),
        ("Martha's Vineyard Times", "mvtimes.com", "Vineyard Haven", "Island Weekly")
    ],
    "Michigan": [
        ("Detroit Free Press", "freep.com", "Detroit", "State Flagship Daily"),
        ("The Detroit News", "detroitnews.com", "Detroit", "Top Metro Daily"),
        ("The Grand Rapids Press / MLive", "mlive.com/grand-rapids", "Grand Rapids", "West Michigan Daily"),
        ("Lansing State Journal", "lansingstatejournal.com", "Lansing", "State Capital Daily"),
        ("The Flint Journal / MLive", "mlive.com/flint", "Flint", "Mid-Michigan Daily"),
        ("Kalamazoo Gazette / MLive", "mlive.com/kalamazoo", "Kalamazoo", "Southwest MI Daily"),
        ("The Ann Arbor News / MLive", "mlive.com/ann-arbor", "Ann Arbor", "University of Michigan Daily"),
        ("Saginaw News / MLive", "mlive.com/saginaw", "Saginaw", "Daily"),
        ("Bay City Times / MLive", "mlive.com/bay-city", "Bay City", "Daily"),
        ("Muskegon Chronicle / MLive", "mlive.com/muskegon", "Muskegon", "Lakeshore Daily"),
        ("Traverse City Record-Eagle", "record-eagle.com", "Traverse City", "Northern MI Daily"),
        ("The Mining Journal", "miningjournal.net", "Marquette", "Upper Peninsula Flagship"),
        ("Battle Creek Enquirer", "battlecreekenquirer.com", "Battle Creek", "Daily"),
        ("The Times Herald", "thetimesherald.com", "Port Huron", "Daily"),
        ("Macomb Daily", "macombdaily.com", "Mount Clemens", "Metro Detroit Daily"),
        ("The Oakland Press", "theoaklandpress.com", "Pontiac", "Metro Detroit Daily"),
        ("Daily Tribune", "dailytribune.com", "Royal Oak", "Daily"),
        ("Jackson Citizen Patriot / MLive", "mlive.com/jackson", "Jackson", "Daily"),
        ("The Daily News", "thedailynews.cc", "Greenville", "Daily"),
        ("Midland Daily News", "ourmidland.com", "Midland", "Daily"),
        ("The Holland Sentinel", "hollandsentinel.com", "Holland", "Daily"),
        ("The Daily Telegram", "lenconnect.com", "Adrian", "Daily"),
        ("Monroe News", "monroenews.com", "Monroe", "Daily"),
        ("Daily Mining Gazette", "mininggazette.com", "Houghton", "Keweenaw Daily")
    ],
    "Minnesota": [
        ("Star Tribune", "startribune.com", "Minneapolis", "State Flagship Daily"),
        ("St. Paul Pioneer Press", "twincities.com", "St. Paul", "Twin Cities Flagship Daily"),
        ("Duluth News Tribune", "duluthnewstribune.com", "Duluth", "North Shore Flagship Daily"),
        ("Post-Bulletin", "postbulletin.com", "Rochester", "Mayo Clinic Region Daily"),
        ("St. Cloud Times", "sctimes.com", "St. Cloud", "Central MN Daily"),
        ("The Free Press", "mankatofreepress.com", "Mankato", "South Central MN Daily"),
        ("The Forum of Fargo-Moorhead", "inforum.com", "Moorhead / Fargo", "Red River Valley Daily"),
        ("Winona Daily News", "winonadailynews.com", "Winona", "Daily"),
        ("Albert Lea Tribune", "albertleatribune.com", "Albert Lea", "Daily"),
        ("Austin Daily Herald", "austindailyherald.com", "Austin", "Daily"),
        ("Brainerd Dispatch", "brainerddispatch.com", "Brainerd", "Daily"),
        ("Faribault Daily News", "southernminn.com/faribault_daily_news", "Faribault", "Daily"),
        ("Owatonna People's Press", "southernminn.com/owatonna_peoples_press", "Owatonna", "Daily"),
        ("Fergus Falls Daily Journal", "fergusfallsjournal.com", "Fergus Falls", "Daily"),
        ("Marshall Independent", "marshallindependent.com", "Marshall", "Daily"),
        ("Worthington Daily Globe", "dglobe.com", "Worthington", "Daily"),
        ("West Central Tribune", "wctrib.com", "Willmar", "Daily"),
        ("Bemidji Pioneer", "bemidjipioneer.com", "Bemidji", "Daily")
    ],
    "Mississippi": [
        ("The Clarion-Ledger", "clarionledger.com", "Jackson", "State Flagship Daily"),
        ("Sun Herald", "sunherald.com", "Biloxi / Gulfport", "Gulf Coast Flagship Daily"),
        ("Northeast Mississippi Daily Journal", "djournal.com", "Tupelo", "Tupelo Daily"),
        ("Hattiesburg American", "hattiesburgamerican.com", "Hattiesburg", "Pine Belt Daily"),
        ("The Vicksburg Post", "vicksburgpost.com", "Vicksburg", "Historic River Daily"),
        ("The Commercial Dispatch", "cdispatch.com", "Columbus / Starkville", "Golden Triangle Daily"),
        ("The Oxford Eagle", "oxfordeagle.com", "Oxford", "Ole Miss Region Daily"),
        ("The Natchez Democrat", "natchezdemocrat.com", "Natchez", "Daily"),
        ("Enterprise-Journal", "enterprise-journal.com", "McComb", "Daily"),
        ("The Meridian Star", "meridianstar.com", "Meridian", "Daily"),
        ("The Greenwood Commonwealth", "gwcommonwealth.com", "Greenwood", "Delta Daily"),
        ("Delta Democrat Times", "ddtonline.com", "Greenville", "Delta Daily"),
        ("The Daily Leader", "dailyleader.com", "Brookhaven", "Daily"),
        ("The Daily Corinthian", "dailycorinthian.com", "Corinth", "Daily"),
        ("Picayune Item", "picayuneitem.com", "Picayune", "Daily")
    ],
    "Missouri": [
        ("St. Louis Post-Dispatch", "stltoday.com", "St. Louis", "State Flagship Daily"),
        ("The Kansas City Star", "kansascity.com", "Kansas City", "Western MO Flagship Daily"),
        ("Springfield News-Leader", "news-leader.com", "Springfield", "Ozarks Flagship Daily"),
        ("Columbia Daily Tribune", "columbiatribune.com", "Columbia", "Mizzou Region Daily"),
        ("Columbia Missourian", "columbiamissourian.com", "Columbia", "University of Missouri"),
        ("Jefferson City News Tribune", "newstribune.com", "Jefferson City", "State Capital Daily"),
        ("St. Joseph News-Press", "newspressnow.com", "St. Joseph", "Top Daily"),
        ("The Joplin Globe", "joplinglobe.com", "Joplin", "Southwest MO Daily"),
        ("Southeast Missourian", "semissourian.com", "Cape Girardeau", "Southeast MO Daily"),
        ("The Examiner", "examiner.net", "Independence", "Daily"),
        ("Hannibal Courier-Post", "hannibal.net", "Hannibal", "Daily"),
        ("Sedalia Democrat", "sedaliademocrat.com", "Sedalia", "Daily"),
        ("The Daily Statesman", "dailystatesman.com", "Dexter", "Daily"),
        ("Daily American Republic", "darnews.com", "Poplar Bluff", "Daily"),
        ("Kirksville Daily Express", "kirksvilledailyexpress.com", "Kirksville", "Daily"),
        ("Moberly Monitor-Index", "moberlymonitor.com", "Moberly", "Daily"),
        ("West Plains Daily Quill", "westplainsdailyquill.net", "West Plains", "Daily"),
        ("The Rolla Daily News", "therolladailynews.com", "Rolla", "Daily"),
        ("Lake Sun", "lakenewsonline.com", "Lake of the Ozarks", "Daily")
    ],
    "Montana": [
        ("The Billings Gazette", "billingsgazette.com", "Billings", "State Flagship Daily"),
        ("Missoulian", "missoulian.com", "Missoula", "Western MT Flagship Daily"),
        ("Independent Record", "helenair.com", "Helena", "State Capital Daily"),
        ("Great Falls Tribune", "greatfallstribune.com", "Great Falls", "Central MT Daily"),
        ("Bozeman Daily Chronicle", "bozemandailychronicle.com", "Bozeman", "Gallatin Valley Daily"),
        ("The Montana Standard", "mtstandard.com", "Butte", "Historic Mining Daily"),
        ("Daily Inter Lake", "dailyinterlake.com", "Kalispell", "Flathead Valley Daily"),
        ("Havre Daily News", "havredailynews.com", "Havre", "Hi-Line Daily"),
        ("The Livingston Enterprise", "livingstonenterprise.com", "Livingston", "Daily"),
        ("Miles City Star", "milescitystar.com", "Miles City", "Eastern MT Daily"),
        ("Sidney Herald", "sidneyherald.com", "Sidney", "Bi-Weekly"),
        ("Glendive Ranger-Review", "rangerreview.com", "Glendive", "Semi-Weekly"),
        ("The Western News", "thewesternnews.com", "Libby", "Semi-Weekly"),
        ("Whitefish Pilot", "whitefishpilot.com", "Whitefish", "Weekly"),
        ("Big Sky Weekly", "explorebigsky.com", "Big Sky", "Bi-Weekly")
    ],
    "Nebraska": [
        ("Omaha World-Herald", "omaha.com", "Omaha", "State Flagship Daily"),
        ("Lincoln Journal Star", "journalstar.com", "Lincoln", "State Capital Flagship Daily"),
        ("The Grand Island Independent", "theindependent.com", "Grand Island", "Central NE Daily"),
        ("Kearney Hub", "kearneyhub.com", "Kearney", "Central NE Daily"),
        ("Scottsbluff Star-Herald", "starherald.com", "Scottsbluff", "Panhandle Daily"),
        ("North Platte Telegraph", "nptelegraph.com", "North Platte", "Daily"),
        ("Norfolk Daily News", "norfolkdailynews.com", "Norfolk", "Daily"),
        ("Fremont Tribune", "fremonttribune.com", "Fremont", "Daily"),
        ("Columbus Telegram", "columbustelegram.com", "Columbus", "Daily"),
        ("Beatrice Daily Sun", "beatricedailysun.com", "Beatrice", "Daily"),
        ("Hastings Tribune", "hastingstribune.com", "Hastings", "Daily"),
        ("York News-Times", "yorknewstimes.com", "York", "Daily"),
        ("McCook Gazette", "mccookgazette.com", "McCook", "Daily"),
        ("Alliance Times-Herald", "alliancetimes.com", "Alliance", "Daily"),
        ("Sidney Sun-Telegraph", "suntelegraph.com", "Sidney", "Semi-Weekly")
    ],
    "Nevada": [
        ("Las Vegas Review-Journal", "reviewjournal.com", "Las Vegas", "State Flagship Daily"),
        ("Las Vegas Sun", "lasvegassun.com", "Las Vegas", "Pulitzer Prize Winning Daily"),
        ("Reno Gazette-Journal", "rgj.com", "Reno", "Northern NV Flagship Daily"),
        ("Nevada Appeal", "nevadaappeal.com", "Carson City", "State Capital Daily"),
        ("Elko Daily Free Press", "elkodaily.com", "Elko", "Northeast NV Daily"),
        ("The Record-Courier", "recordcourier.com", "Gardnerville / Minden", "Carson Valley Daily"),
        ("Pahrump Valley Times", "pvtimes.com", "Pahrump", "Nye County Semi-Weekly"),
        ("Lahontan Valley News", "nevadaappeal.com/lvn", "Fallon", "Churchill County"),
        ("The Ely Times", "elynews.com", "Ely", "White Pine Weekly"),
        ("Humboldt Sun", "humboldtsun.com", "Winnemucca", "Semi-Weekly"),
        ("Boulder City Review", "bouldercityreview.com", "Boulder City", "Weekly"),
        ("Henderson RoundUp", "reviewjournal.com/local/henderson", "Henderson", "Weekly")
    ],
    "New Hampshire": [
        ("New Hampshire Union Leader", "unionleader.com", "Manchester", "State Flagship Daily"),
        ("Concord Monitor", "concordmonitor.com", "Concord", "State Capital Daily"),
        ("The Telegraph", "nashuatelegraph.com", "Nashua", "Southern NH Daily"),
        ("Portsmouth Herald / Seacoastonline", "seacoastonline.com", "Portsmouth", "Seacoast Flagship Daily"),
        ("Foster's Daily Democrat", "fosters.com", "Dover", "Daily"),
        ("Keene Sentinel", "sentinelsource.com", "Keene", "Monadnock Region Daily"),
        ("Valley News", "vnews.com", "West Lebanon / Upper Valley", "Upper Valley Daily"),
        ("The Laconia Daily Sun", "laconiadailysun.com", "Laconia", "Lakes Region Daily"),
        ("The Conway Daily Sun", "conwaydailysun.com", "North Conway", "White Mountains Daily"),
        ("The Berlin Sun", "berlinsun.com", "Berlin", "North Country Daily"),
        ("Caledonian-Record", "caledonianrecord.com", "Littleton / St. Johnsbury", "Daily"),
        ("Monadnock Ledger-Transcript", "ledgertranscript.com", "Peterborough", "Semi-Weekly")
    ],
    "New Jersey": [
        ("The Star-Ledger / NJ.com", "nj.com", "Newark", "State Flagship Daily"),
        ("The Record", "northjersey.com", "Bergen County / Woodland Park", "North Jersey Flagship Daily"),
        ("Asbury Park Press", "app.com", "Asbury Park / Neptune", "Jersey Shore Flagship Daily"),
        ("The Press of Atlantic City", "pressofatlanticcity.com", "Atlantic City", "South Jersey Shore Daily"),
        ("Courier-Post", "courierpostonline.com", "Cherry Hill / Camden", "South Jersey Metro Daily"),
        ("Home News Tribune", "mycentraljersey.com", "Somerville / New Brunswick", "Central Jersey Daily"),
        ("Daily Record", "dailyrecord.com", "Morristown", "Morris County Daily"),
        ("The Times", "nj.com/times", "Trenton", "State Capital Daily"),
        ("The Trentonian", "trentonian.com", "Trenton", "Daily"),
        ("The Jersey Journal", "nj.com/jjournal", "Jersey City", "Hudson County Daily"),
        ("Burlington County Times", "burlingtoncountytimes.com", "Willingboro", "Daily"),
        ("South Jersey Times", "nj.com/south-jersey-towns", "Woodbury / Mullica Hill", "Daily"),
        ("The Daily Journal", "thedailyjournal.com", "Vineland", "Cumberland County Daily"),
        ("New Jersey Herald", "njherald.com", "Newton", "Sussex County Daily"),
        ("Cape May County Herald", "capemaycountyherald.com", "Rio Grande / Cape May", "Weekly"),
        ("The Ocean Star", "theoceanstar.com", "Point Pleasant Beach", "Weekly"),
        ("The Coast Star", "thecoaststar.com", "Manasquan", "Weekly")
    ],
    "New Mexico": [
        ("Albuquerque Journal", "abqjournal.com", "Albuquerque", "State Flagship Daily"),
        ("The Santa Fe New Mexican", "santafenewmexican.com", "Santa Fe", "State Capital Flagship Daily"),
        ("Las Cruces Sun-News", "lcsun-news.com", "Las Cruces", "Southern NM Daily"),
        ("Roswell Daily Record", "rdrnews.com", "Roswell", "Pecos Valley Daily"),
        ("Farmington Daily Times", "daily-times.com", "Farmington", "Four Corners Daily"),
        ("The Taos News", "taosnews.com", "Taos", "Award-Winning Weekly"),
        ("The Eastern New Mexico News", "easternnewmexiconews.com", "Clovis / Portales", "Daily"),
        ("Carlsbad Current-Argus", "currentargus.com", "Carlsbad", "Daily"),
        ("Hobbs News-Sun", "hobbsnews.com", "Hobbs", "Daily"),
        ("Gallup Independent", "gallupindependent.com", "Gallup", "Daily"),
        ("Silver City Daily Press", "scdailypress.com", "Silver City", "Daily"),
        ("Alamogordo Daily News", "alamogordonews.com", "Alamogordo", "Daily"),
        ("The Rio Grande Sun", "riograndesun.com", "Española", "Weekly"),
        ("Ruidoso News", "ruidosonews.com", "Ruidoso", "Semi-Weekly"),
        ("Los Alamos Reporter", "losalamosreporter.com", "Los Alamos", "Daily")
    ],
    "New York": [
        ("The New York Times", "nytimes.com", "New York City", "National & International Flagship"),
        ("The Wall Street Journal", "wsj.com", "New York City", "Leading Financial Daily"),
        ("New York Post", "nypost.com", "New York City", "Major Metro Daily"),
        ("New York Daily News", "nydailynews.com", "New York City", "Major Metro Daily"),
        ("Newsday", "newsday.com", "Long Island", "Long Island Flagship Daily"),
        ("The Buffalo News", "buffalonews.com", "Buffalo", "Western NY Flagship Daily"),
        ("Democrat and Chronicle", "democratandchronicle.com", "Rochester", "Rochester Flagship Daily"),
        ("The Post-Standard / Syracuse.com", "syracuse.com", "Syracuse", "Central NY Flagship Daily"),
        ("Times Union", "timesunion.com", "Albany", "State Capital Flagship Daily"),
        ("The Journal News / lohud.com", "lohud.com", "White Plains / Westchester", "Lower Hudson Daily"),
        ("Staten Island Advance / SILive", "silive.com", "Staten Island", "Borough Daily"),
        ("The Daily Gazette", "dailygazette.com", "Schenectady", "Capital Region Daily"),
        ("The Post-Star", "poststar.com", "Glens Falls", "Adirondack Region Daily"),
        ("The Post-Journal", "post-journal.com", "Jamestown", "Chautauqua County Daily"),
        ("Observer", "observertoday.com", "Dunkirk", "Daily"),
        ("Olean Times Herald", "oleantimesherald.com", "Olean", "Daily"),
        ("Star-Gazette", "stargazette.com", "Elmira", "Southern Tier Daily"),
        ("The Leader", "the-leader.com", "Corning", "Daily"),
        ("Press & Sun-Bulletin", "pressconnects.com", "Binghamton", "Southern Tier Daily"),
        ("The Ithaca Journal", "theithacajournal.com", "Ithaca", "Cornell / Tompkins Daily"),
        ("The Citizen", "auburnpub.com", "Auburn", "Finger Lakes Daily"),
        ("Daily Messenger", "mpnnow.com", "Canandaigua", "Finger Lakes Daily"),
        ("Finger Lakes Times", "fltimes.com", "Geneva", "Daily"),
        ("Times Herald-Record", "recordonline.com", "Middletown", "Mid-Hudson Daily"),
        ("Poughkeepsie Journal", "poughkeepsiejournal.com", "Poughkeepsie", "Dutchess County Daily"),
        ("Daily Freeman", "dailyfreeman.com", "Kingston", "Ulster County Daily"),
        ("The Register-Star", "hudsonvalley360.com", "Hudson", "Columbia County Daily"),
        ("The Daily Mail", "hudsonvalley360.com", "Catskill", "Greene County Daily"),
        ("The Leader-Herald", "leaderherald.com", "Gloversville", "Fulton-Montgomery Daily"),
        ("The Recorder", "recordernews.com", "Amsterdam", "Daily"),
        ("The Daily Star", "thedailystar.com", "Oneonta", "Otsego County Daily"),
        ("Watertown Daily Times", "nny360.com", "Watertown", "North Country Daily"),
        ("Press-Republican", "pressrepublican.com", "Plattsburgh", "Lake Champlain Daily"),
        ("Adirondack Daily Enterprise", "adirondackdailyenterprise.com", "Saranac Lake", "Olympic Region Daily"),
        ("Lake Placid News", "lakeplacidnews.com", "Lake Placid", "Weekly"),
        ("The Saratogian", "saratogian.com", "Saratoga Springs", "Daily"),
        ("The Troy Record", "troyrecord.com", "Troy", "Rensselaer County Daily"),
        ("Niagara Gazette", "niagara-gazette.com", "Niagara Falls", "Daily"),
        ("Lockport Union-Sun & Journal", "lockportjournal.com", "Lockport", "Daily"),
        ("Batavia Daily News", "thedailynewsonline.com", "Batavia", "Daily"),
        ("Rome Sentinel", "romesentinel.com", "Rome", "Oneida County Daily"),
        ("Observer-Dispatch", "uticaod.com", "Utica", "Mohawk Valley Daily"),
        ("The Cortland Standard", "cortlandstandard.com", "Cortland", "Daily")
    ],
    "North Carolina": [
        ("The Charlotte Observer", "charlotteobserver.com", "Charlotte", "State Flagship Daily"),
        ("The News & Observer", "newsobserver.com", "Raleigh", "Research Triangle Flagship Daily"),
        ("Greensboro News & Record", "greensboro.com", "Greensboro", "Piedmont Triad Daily"),
        ("Winston-Salem Journal", "journalnow.com", "Winston-Salem", "Piedmont Triad Daily"),
        ("Asheville Citizen-Times", "citizen-times.com", "Asheville", "Western NC Flagship Daily"),
        ("Star-News", "starnewsonline.com", "Wilmington", "Cape Fear Region Daily"),
        ("The Herald-Sun", "heraldsun.com", "Durham", "Research Triangle Daily"),
        ("The Fayetteville Observer", "fayobserver.com", "Fayetteville", "Sandhills Region Daily"),
        ("The Daily News", "jdnews.com", "Jacksonville", "Camp Lejeune Region Daily"),
        ("High Point Enterprise", "hpenews.com", "High Point", "Daily"),
        ("Times-News", "thetimesnews.com", "Burlington", "Daily"),
        ("The Daily Reflector", "reflector.com", "Greenville", "Eastern NC Daily"),
        ("Salisbury Post", "salisburypost.com", "Salisbury", "Daily"),
        ("The Dispatch", "the-dispatch.com", "Lexington", "Daily"),
        ("The Gaston Gazette", "gastongazette.com", "Gastonia", "Daily"),
        ("The Shelby Star", "shelbystar.com", "Shelby", "Daily"),
        ("Hickory Daily Record", "hickoryrecord.com", "Hickory", "Daily"),
        ("The Courier-Tribune", "courier-tribune.com", "Asheboro", "Daily"),
        ("The Daily Courier", "thedigitalcourier.com", "Forest City", "Daily"),
        ("Statesville Record & Landmark", "recordandlandmark.com", "Statesville", "Daily"),
        ("The Daily Record", "mydailyrecord.com", "Dunn", "Daily"),
        ("Kinston Free Press", "kinston.com", "Kinston", "Daily"),
        ("New Bern Sun Journal", "newbernsj.com", "New Bern", "Daily"),
        ("The Wilson Times", "wilsontimes.com", "Wilson", "Daily"),
        ("The Daily Advance", "dailyadvance.com", "Elizabeth City", "Daily"),
        ("The Outer Banks Voice", "outerbanksvoice.com", "Kill Devil Hills", "Daily Online"),
        ("The Sanford Herald", "sanfordherald.com", "Sanford", "Daily"),
        ("Rocky Mount Telegram", "rockymounttelegram.com", "Rocky Mount", "Daily"),
        ("Henderson Dispatch", "hendersondispatch.com", "Henderson", "Daily"),
        ("The Mount Airy News", "mtairynews.com", "Mount Airy", "Daily")
    ],
    "North Dakota": [
        ("The Forum of Fargo-Moorhead", "inforum.com", "Fargo", "State Flagship Daily"),
        ("The Bismarck Tribune", "bismarcktribune.com", "Bismarck", "State Capital Flagship Daily"),
        ("Grand Forks Herald", "grandforksherald.com", "Grand Forks", "UND Region Daily"),
        ("Minot Daily News", "minotdailynews.com", "Minot", "North Central ND Daily"),
        ("The Dickinson Press", "thedickinsonpress.com", "Dickinson", "Southwest ND Daily"),
        ("Williston Herald", "willistonherald.com", "Williston", "Bakken Region Daily"),
        ("Jamestown Sun", "jamestownsun.com", "Jamestown", "Daily"),
        ("Devils Lake Journal", "devilslakejournal.com", "Devils Lake", "Daily"),
        ("Valley City Times-Record", "times-online.com", "Valley City", "Daily"),
        ("Wahpeton Daily News", "wahpetondailynews.com", "Wahpeton", "Daily")
    ],
    "Ohio": [
        ("The Plain Dealer / cleveland.com", "cleveland.com", "Cleveland", "State Flagship Daily"),
        ("The Columbus Dispatch", "dispatch.com", "Columbus", "State Capital Flagship Daily"),
        ("The Cincinnati Enquirer", "cincinnati.com", "Cincinnati", "Tristate Flagship Daily"),
        ("The Blade", "toledoblade.com", "Toledo", "Northwest Ohio Flagship Daily"),
        ("Akron Beacon Journal", "beaconjournal.com", "Akron", "Summit County Daily"),
        ("Dayton Daily News", "daytondailynews.com", "Dayton", "Miami Valley Flagship Daily"),
        ("The Canton Repository", "cantonrep.com", "Canton", "Stark County Daily"),
        ("The Vindicator / Tribune Chronicle", "vindy.com", "Youngstown / Warren", "Mahoning Valley Daily"),
        ("The Chronicle-Telegram", "chroniclet.com", "Elyria", "Lorain County Daily"),
        ("The Morning Journal", "morningjournal.com", "Lorain", "Daily"),
        ("Springfield News-Sun", "springfieldnewssun.com", "Springfield", "Daily"),
        ("The Lima News", "limaohio.com", "Lima", "West Central OH Daily"),
        ("Mansfield News Journal", "mansfieldnewsjournal.com", "Mansfield", "Daily"),
        ("The Times-Reporter", "timesreporter.com", "New Philadelphia", "Daily"),
        ("Newark Advocate", "newarkadvocate.com", "Newark", "Licking County Daily"),
        ("Zanesville Times Recorder", "zanesvilletimesrecorder.com", "Zanesville", "Daily"),
        ("Chillicothe Gazette", "chillicothegazette.com", "Chillicothe", "Daily"),
        ("Lancaster Eagle-Gazette", "lancastereaglegazette.com", "Lancaster", "Daily"),
        ("The Marion Star", "marionstar.com", "Marion", "Daily"),
        ("Sandusky Register", "sanduskyregister.com", "Sandusky", "Daily"),
        ("Norwalk Reflector", "norwalkreflector.com", "Norwalk", "Daily"),
        ("The Courier", "thecourier.com", "Findlay", "Daily"),
        ("The Advertiser-Tribune", "advertiser-tribune.com", "Tiffin", "Daily"),
        ("Portsmouth Daily Times", "portsmouth-dailytimes.com", "Portsmouth", "Daily"),
        ("The Herald-Star", "hsconnect.com", "Steubenville", "Daily"),
        ("The Daily Record", "the-daily-record.com", "Wooster", "Daily"),
        ("The Daily Jeffersonian", "daily-jeff.com", "Cambridge", "Daily"),
        ("Ashtabula Star Beacon", "starbeacon.com", "Ashtabula", "Daily"),
        ("The News-Herald", "news-herald.com", "Willoughby / Lake County", "Daily"),
        ("The Athens Messenger", "athensmessenger.com", "Athens", "Ohio University Daily")
    ],
    "Oklahoma": [
        ("The Oklahoman", "oklahoman.com", "Oklahoma City", "State Flagship Daily"),
        ("Tulsa World", "tulsaworld.com", "Tulsa", "Northeast OK Flagship Daily"),
        ("The Norman Transcript", "normantranscript.com", "Norman", "OU Region Daily"),
        ("The Lawton Constitution", "swoknews.com", "Lawton", "Southwest OK Daily"),
        ("Enid News & Eagle", "enidnews.com", "Enid", "Northwest OK Daily"),
        ("Stillwater News Press", "stwnewspress.com", "Stillwater", "Oklahoma State University Daily"),
        ("Muskogee Phoenix", "muskogeephoenix.com", "Muskogee", "Daily"),
        ("The Shawnee News-Star", "news-star.com", "Shawnee", "Daily"),
        ("The Ardmoreite", "ardmoreite.com", "Ardmore", "Daily"),
        ("Bartlesville Examiner-Enterprise", "examiner-enterprise.com", "Bartlesville", "Daily"),
        ("Ponca City News", "poncacitynews.com", "Ponca City", "Daily"),
        ("McAlester News-Capital", "mcalesternews.com", "McAlester", "Daily"),
        ("Duncan Banner", "duncanbanner.com", "Duncan", "Daily"),
        ("Tahlequah Daily Press", "tahlequahdailypress.com", "Tahlequah", "Daily"),
        ("Altus Times", "altustimes.com", "Altus", "Daily"),
        ("Claremore Daily Progress", "claremoreprogress.com", "Claremore", "Daily")
    ],
    "Oregon": [
        ("The Oregonian / OregonLive", "oregonlive.com", "Portland", "State Flagship Daily"),
        ("The Register-Guard", "registerguard.com", "Eugene", "University of Oregon Daily"),
        ("Statesman Journal", "statesmanjournal.com", "Salem", "State Capital Flagship Daily"),
        ("The Bulletin", "bendbulletin.com", "Bend", "Central Oregon Flagship Daily"),
        ("Mail Tribune / Rogue Valley Times", "rv-times.com", "Medford", "Southern Oregon Flagship"),
        ("Corvallis Gazette-Times", "gazettetimes.com", "Corvallis", "Oregon State University Daily"),
        ("Albany Democrat-Herald", "democratherald.com", "Albany", "Willamette Valley Daily"),
        ("The Daily Astorian", "dailyastorian.com", "Astoria", "Coastal Flagship Daily"),
        ("The World", "theworldlink.com", "Coos Bay", "South Coast Daily"),
        ("East Oregonian", "eastoregonian.com", "Pendleton", "Eastern Oregon Daily"),
        ("The Observer", "lagrandeobserver.com", "La Grande", "Northeast OR Daily"),
        ("The Baker City Herald", "bakercityherald.com", "Baker City", "Daily"),
        ("The Dalles Chronicle / Columbia Gorge News", "columbiagorgenews.com", "The Dalles", "Columbia Gorge Daily"),
        ("Argus Observer", "argusobserver.com", "Ontario", "Treasure Valley Daily"),
        ("Herald and News", "heraldandnews.com", "Klamath Falls", "Daily"),
        ("Curry Coastal Pilot", "currypilot.com", "Brookings", "Semi-Weekly"),
        ("News-Register", "newsregister.com", "McMinnville", "Semi-Weekly"),
        ("Portland Tribune", "pamplinmedia.com", "Portland", "Weekly")
    ],
    "Pennsylvania": [
        ("The Philadelphia Inquirer", "inquirer.com", "Philadelphia", "Pulitzer Prize Winning Flagship"),
        ("Pittsburgh Post-Gazette", "post-gazette.com", "Pittsburgh", "Western PA Flagship Daily"),
        ("Pittsburgh Tribune-Review / TribLIVE", "triblive.com", "Pittsburgh / Greensburg", "Western PA Daily"),
        ("The Patriot-News / PennLive", "pennlive.com", "Harrisburg", "State Capital Flagship Daily"),
        ("The Morning Call", "mcall.com", "Allentown", "Lehigh Valley Flagship Daily"),
        ("Erie Times-News / GoErie", "goerie.com", "Erie", "Northwest PA Flagship Daily"),
        ("LNP / LancasterOnline", "lancasteronline.com", "Lancaster", "Lancaster County Daily"),
        ("Reading Eagle", "readingeagle.com", "Reading", "Berks County Daily"),
        ("York Daily Record", "ydr.com", "York", "York County Daily"),
        ("The Times-Tribune", "thetimes-tribune.com", "Scranton", "Northeast PA Flagship Daily"),
        ("The Citizens' Voice", "citizensvoice.com", "Wilkes-Barre", "Wyoming Valley Daily"),
        ("Times Leader", "timesleader.com", "Wilkes-Barre", "Wyoming Valley Daily"),
        ("Bucks County Courier Times", "buckscountycouriertimes.com", "Levittown", "Bucks County Daily"),
        ("The Intelligencer", "theintell.com", "Doylestown", "Central Bucks Daily"),
        ("Daily Local News", "dailylocal.com", "West Chester", "Chester County Daily"),
        ("Delaware County Daily Times", "delcotimes.com", "Primos / Delco", "Delaware County Daily"),
        ("The Mercury", "pottsmerc.com", "Pottstown", "Daily"),
        ("The Reporter", "thereporteronline.com", "Lansdale", "Daily"),
        ("The Times Herald", "timesherald.com", "Norristown", "Daily"),
        ("Altoona Mirror", "altoonamirror.com", "Altoona", "Daily"),
        ("Centre Daily Times", "centredaily.com", "State College", "Penn State Daily"),
        ("Williamsport Sun-Gazette", "sungazette.com", "Williamsport", "Lycoming County Daily"),
        ("The Daily Item", "dailyitem.com", "Sunbury", "Central Susquehanna Daily"),
        ("The Standard-Speaker", "standardspeaker.com", "Hazleton", "Daily"),
        ("Pottsville Republican Herald", "republicanherald.com", "Pottsville", "Schuylkill County Daily"),
        ("Lebanon Daily News", "ldnews.com", "Lebanon", "Daily"),
        ("Hanover Evening Sun", "eveningsun.com", "Hanover", "Daily"),
        ("The Sentinel", "cumberlink.com", "Carlisle", "Cumberland County Daily"),
        ("Public Opinion", "publicopiniononline.com", "Chambersburg", "Franklin County Daily"),
        ("The Herald", "sharonherald.com", "Sharon", "Shenango Valley Daily"),
        ("The Derrick / The News-Herald", "thederrick.com", "Oil City / Franklin", "Oil Region Daily"),
        ("The Bradford Era", "bradfordera.com", "Bradford", "Daily"),
        ("The Indiana Gazette", "indianagazette.com", "Indiana", "Daily"),
        ("Butler Eagle", "butlereagle.com", "Butler", "Daily"),
        ("Beaver County Times", "timesonline.com", "Beaver", "Daily"),
        ("Observer-Reporter", "observer-reporter.com", "Washington", "Daily"),
        ("The Daily Courier", "dailycourier.com", "Connellsville", "Daily"),
        ("The Herald-Standard", "heraldstandard.com", "Uniontown", "Daily"),
        ("The Daily American", "dailyamerican.com", "Somerset", "Daily"),
        ("The Tribune-Democrat", "tribdem.com", "Johnstown", "Cambria County Daily"),
        ("Pocono Record", "poconorecord.com", "Stroudsburg", "Pocono Mountains Daily"),
        ("The Wayne Independent", "wayneindependent.com", "Honesdale", "Daily")
    ],
    "Rhode Island": [
        ("The Providence Journal", "providencejournal.com", "Providence", "State Flagship Daily"),
        ("The Westerly Sun", "thewesterlysun.com", "Westerly", "South County Daily"),
        ("The Newport Daily News", "newportri.com", "Newport", "Aquidneck Island Daily"),
        ("The Pawtucket Times", "pawtuckettimes.com", "Pawtucket", "Blackstone Valley Daily"),
        ("The Woonsocket Call", "woonsocketcall.com", "Woonsocket", "Daily"),
        ("The Valley Breeze", "valleybreeze.com", "Cumberland / Lincoln", "Weekly Group"),
        ("Warwick Beacon", "warwickonline.com", "Warwick", "Weekly"),
        ("Cranston Herald", "cranstononline.com", "Cranston", "Weekly"),
        ("The Narragansett Times", "ricentral.com", "Narragansett", "Weekly"),
        ("East Bay Media Group", "eastbayri.com", "Bristol / Warren / Barrington", "East Bay Weeklies")
    ],
    "South Carolina": [
        ("The Post and Courier", "postandcourier.com", "Charleston", "Pulitzer Prize Winning Flagship"),
        ("The State", "thestate.com", "Columbia", "State Capital Flagship Daily"),
        ("The Greenville News", "greenvilleonline.com", "Greenville", "Upstate Flagship Daily"),
        ("The Sun News", "myrtlebeachonline.com", "Myrtle Beach", "Grand Strand Flagship Daily"),
        ("The Herald", "heraldonline.com", "Rock Hill", "York County Daily"),
        ("Spartanburg Herald-Journal", "goupstate.com", "Spartanburg", "Upstate Daily"),
        ("The Island Packet", "islandpacket.com", "Hilton Head Island", "Lowcountry Daily"),
        ("The Beaufort Gazette", "islandpacket.com/beaufort-gazette", "Beaufort", "Lowcountry Daily"),
        ("Morning News", "scnow.com", "Florence", "Pee Dee Region Daily"),
        ("The Index-Journal", "indexjournal.com", "Greenwood", "Daily"),
        ("The Times and Democrat", "thetandd.com", "Orangeburg", "Daily"),
        ("Aiken Standard", "aikenstandard.com", "Aiken", "Daily"),
        ("The Sumter Item", "theitem.com", "Sumter", "Daily"),
        ("Anderson Independent Mail", "independentmail.com", "Anderson", "Daily"),
        ("The Union Times", "uniondailytimes.com", "Union", "Daily")
    ],
    "South Dakota": [
        ("Argus Leader", "argusleader.com", "Sioux Falls", "State Flagship Daily"),
        ("Rapid City Journal", "rapidcityjournal.com", "Rapid City", "Black Hills Flagship Daily"),
        ("Aberdeen American News", "aberdeennews.com", "Aberdeen", "Northeast SD Daily"),
        ("Watertown Public Opinion", "thepublicopinion.com", "Watertown", "Daily"),
        ("The Daily Republic", "mitchellrepublic.com", "Mitchell", "Daily"),
        ("Brookings Register", "brookingsregister.com", "Brookings", "SDSU Region Daily"),
        ("Yankton Daily Press & Dakotan", "yankton.net", "Yankton", "Oldest SD Daily"),
        ("Capital Journal", "capjournal.com", "Pierre", "State Capital Daily"),
        ("Huron Plainsman", "plainsman.com", "Huron", "Daily"),
        ("Black Hills Pioneer", "bhpioneer.com", "Spearfish", "Daily"),
        ("Madison Daily Leader", "madisondailyleader.com", "Madison", "Daily")
    ],
    "Tennessee": [
        ("The Tennessean", "tennessean.com", "Nashville", "State Flagship Daily"),
        ("The Commercial Appeal", "commercialappeal.com", "Memphis", "Mid-South Flagship Daily"),
        ("Knoxville News Sentinel", "knoxnews.com", "Knoxville", "East TN Flagship Daily"),
        ("Chattanooga Times Free Press", "timesfreepress.com", "Chattanooga", "Top Daily"),
        ("The Daily News Journal", "dnj.com", "Murfreesboro", "MTSU Region Daily"),
        ("The Leaf-Chronicle", "theleafchronicle.com", "Clarksville", "Fort Campbell Region Daily"),
        ("The Jackson Sun", "jacksonsun.com", "Jackson", "West TN Daily"),
        ("Johnson City Press", "johnsoncitypress.com", "Johnson City", "Tri-Cities Daily"),
        ("Kingsport Times-News", "timesnews.net", "Kingsport", "Tri-Cities Daily"),
        ("The Daily Times", "thedailytimes.com", "Maryville", "Daily"),
        ("Bristol Herald Courier", "heraldcourier.com", "Bristol", "Tri-Cities Daily"),
        ("The Daily Herald", "columbiadailyherald.com", "Columbia", "Daily"),
        ("The Oak Ridger", "oakridger.com", "Oak Ridge", "Daily"),
        ("Cleveland Daily Banner", "clevelandbanner.com", "Cleveland", "Daily"),
        ("The Greeneville Sun", "greenevillesun.com", "Greeneville", "Daily"),
        ("Herald-Citizen", "herald-citizen.com", "Cookeville", "Daily"),
        ("The Lebanon Democrat", "lebanondemocrat.com", "Lebanon", "Daily"),
        ("Dyersburg State Gazette", "stategazette.com", "Dyersburg", "Daily"),
        ("The Daily Post-Athenian", "dpa.thepostathenian.com", "Athens", "Daily"),
        ("Morristown Citizen Tribune", "citizentribune.com", "Morristown", "Daily")
    ],
    "Texas": [
        ("Houston Chronicle", "houstonchronicle.com", "Houston", "Largest TX Newspaper / Flagship"),
        ("The Dallas Morning News", "dallasnews.com", "Dallas", "North Texas Flagship Daily"),
        ("San Antonio Express-News", "expressnews.com", "San Antonio", "South Texas Flagship Daily"),
        ("Austin American-Statesman", "statesman.com", "Austin", "State Capital Flagship Daily"),
        ("Fort Worth Star-Telegram", "star-telegram.com", "Fort Worth", "Tarrant County Flagship Daily"),
        ("El Paso Times", "elpasotimes.com", "El Paso", "Borderplex Flagship Daily"),
        ("Corpus Christi Caller-Times", "caller.com", "Corpus Christi", "Coastal Bend Flagship Daily"),
        ("Lubbock Avalanche-Journal", "lubbockonline.com", "Lubbock", "South Plains Flagship Daily"),
        ("Amarillo Globe-News", "amarillo.com", "Amarillo", "Panhandle Flagship Daily"),
        ("The Monitor", "myrgv.com", "McAllen", "Rio Grande Valley Daily"),
        ("Waco Tribune-Herald", "wacotrib.com", "Waco", "Central Texas Daily"),
        ("Beaumont Enterprise", "beaumontenterprise.com", "Beaumont", "Southeast Texas Daily"),
        ("The Eagle", "theeagle.com", "Bryan-College Station", "Texas A&M Daily"),
        ("Midland Reporter-Telegram", "mrt.com", "Midland", "Permian Basin Daily"),
        ("Odessa American", "oaoa.com", "Odessa", "Permian Basin Daily"),
        ("Abilene Reporter-News", "reporternews.com", "Abilene", "Big Country Daily"),
        ("San Angelo Standard-Times", "gosanangelo.com", "San Angelo", "West Texas Daily"),
        ("Tyler Morning Telegraph", "tylerpaper.com", "Tyler", "East Texas Daily"),
        ("Longview News-Journal", "news-journal.com", "Longview", "East Texas Daily"),
        ("Wichita Falls Times Record News", "timesrecordnews.com", "Wichita Falls", "Daily"),
        ("Valley Morning Star", "myrgv.com", "Harlingen", "Rio Grande Valley Daily"),
        ("The Brownsville Herald", "myrgv.com", "Brownsville", "Rio Grande Valley Daily"),
        ("Laredo Morning Times", "lmtonline.com", "Laredo", "Gateway City Daily"),
        ("The Victoria Advocate", "victoriaadvocate.com", "Victoria", "South Texas Daily"),
        ("Galveston County Daily News", "galvnews.com", "Galveston", "Oldest TX Newspaper"),
        ("The Daily News / Temple Daily Telegram", "tdtnews.com", "Temple", "Daily"),
        ("Killeen Daily Herald", "kdhnews.com", "Killeen", "Fort Cavazos Daily"),
        ("The Facts", "thefacts.com", "Clute / Brazoria", "Brazoria County Daily"),
        ("The Paris News", "theparisnews.com", "Paris", "Daily"),
        ("The Herald Democrat", "heralddemocrat.com", "Sherman / Denison", "Texoma Daily"),
        ("Texarkana Gazette", "texarkanagazette.com", "Texarkana", "Daily"),
        ("The Huntsville Item", "itemonline.com", "Huntsville", "Daily"),
        ("The Baytown Sun", "baytownsun.com", "Baytown", "Daily"),
        ("The Daily Sentinel", "dailysentinel.com", "Nacogdoches", "Daily"),
        ("The Lufkin News", "lufkindailynews.com", "Lufkin", "Daily"),
        ("Greenville Herald-Banner", "heraldbanner.com", "Greenville", "Daily"),
        ("Weatherford Democrat", "weatherforddemocrat.com", "Weatherford", "Daily"),
        ("Corsicana Daily Sun", "corsicanadailysun.com", "Corsicana", "Daily"),
        ("Athens Daily Review", "athensreview.com", "Athens", "Daily"),
        ("The Seguin Gazette", "seguingazette.com", "Seguin", "Daily"),
        ("New Braunfels Herald-Zeitung", "herald-zeitung.com", "New Braunfels", "Daily"),
        ("San Marcos Daily Record", "sanmarcosrecord.com", "San Marcos", "Daily"),
        ("The Kerrville Daily Times", "dailytimes.com", "Kerrville", "Daily"),
        ("Stephenville Empire-Tribune", "empiretribune.com", "Stephenville", "Daily"),
        ("Brownwood Bulletin", "brownwoodtx.com", "Brownwood", "Daily"),
        ("Mineral Wells Index", "mineralwellsindex.com", "Mineral Wells", "Daily"),
        ("Gainesville Daily Register", "gainesvilleregister.com", "Gainesville", "Daily"),
        ("The Port Arthur News", "panews.com", "Port Arthur", "Daily"),
        ("The Orange Leader", "orangeleader.com", "Orange", "Daily"),
        ("Alice Echo-News Journal", "alicetx.com", "Alice", "Daily"),
        ("Del Rio News-Herald", "delrionewsherald.com", "Del Rio", "Daily")
    ],
    "Utah": [
        ("The Salt Lake Tribune", "sltrib.com", "Salt Lake City", "Pulitzer Prize Winning Flagship Daily"),
        ("Deseret News", "deseret.com", "Salt Lake City", "Oldest Continuously Published Daily in UT"),
        ("Standard-Examiner", "standard.net", "Ogden", "Northern Utah Daily"),
        ("Daily Herald", "heraldextra.com", "Provo", "Utah Valley Daily"),
        ("The Spectrum", "thespectrum.com", "St. George", "Southern Utah Daily"),
        ("The Herald Journal", "hjnews.com", "Logan", "Cache Valley Daily"),
        ("Park Record", "parkrecord.com", "Park City", "Summit County Semi-Weekly"),
        ("The Daily Universe", "universe.byu.edu", "Provo", "BYU Daily"),
        ("The Daily Utah Chronicle", "dailyutahchronicle.com", "Salt Lake City", "University of Utah"),
        ("Moab Sun News", "moabsunnews.com", "Moab", "Weekly"),
        ("The Times-Independent", "moabtimes.com", "Moab", "Weekly"),
        ("Davis Clipper", "clippertoday.com", "Bountiful", "Weekly"),
        ("The Vernal Express", "ubmedia.biz", "Vernal", "Weekly"),
        ("Uintah Basin Standard", "ubmedia.biz", "Roosevelt", "Weekly"),
        ("San Juan Record", "sjrnews.com", "Monticello", "Weekly")
    ],
    "Vermont": [
        ("The Burlington Free Press", "burlingtonfreepress.com", "Burlington", "State Flagship Daily"),
        ("Rutland Herald", "rutlandherald.com", "Rutland", "Pulitzer Prize Winning Daily"),
        ("Times Argus", "timesargus.com", "Barre / Montpelier", "State Capital Region Daily"),
        ("Brattleboro Reformer", "reformer.com", "Brattleboro", "Southern VT Daily"),
        ("Bennington Banner", "benningtonbanner.com", "Bennington", "Southwest VT Daily"),
        ("The Caledonian-Record", "caledonianrecord.com", "St. Johnsbury", "Northeast Kingdom Daily"),
        ("Seven Days", "sevendaysvt.com", "Burlington", "Leading Independent Weekly"),
        ("VTDigger", "vtdigger.org", "Montpelier", "Statewide Investigative Daily"),
        ("Valley News", "vnews.com", "White River Junction", "Upper Valley Daily"),
        ("Addison County Independent", "addisonindependent.com", "Middlebury", "Semi-Weekly"),
        ("Stowe Reporter", "vtcng.com/stowe_reporter", "Stowe", "Weekly"),
        ("The Newport Daily Express", "newportvermontexpress.com", "Newport", "Weekly")
    ],
    "Virginia": [
        ("Richmond Times-Dispatch", "richmond.com", "Richmond", "State Capital Flagship Daily"),
        ("The Virginian-Pilot", "pilotonline.com", "Norfolk / Virginia Beach", "Hampton Roads Flagship Daily"),
        ("Daily Press", "dailypress.com", "Newport News / Hampton", "Hampton Roads Daily"),
        ("The Roanoke Times", "roanoke.com", "Roanoke", "Southwest VA Flagship Daily"),
        ("The Washington Post (Northern VA)", "washingtonpost.com/local/virginia-politics", "Northern Virginia", "NoVA Metro Flagship"),
        ("The Daily Progress", "dailyprogress.com", "Charlottesville", "UVA Region Daily"),
        ("The Free Lance-Star", "fredericksburg.com", "Fredericksburg", "Central VA Daily"),
        ("Bristol Herald Courier", "heraldcourier.com", "Bristol", "Tri-Cities Daily"),
        ("News & Record", "wset.com", "South Boston", "Daily"),
        ("The News & Advance", "newsadvance.com", "Lynchburg", "Central VA Daily"),
        ("Danville Register & Bee", "godanriver.com", "Danville", "Southside Daily"),
        ("Daily News-Record", "dnronline.com", "Harrisonburg", "Shenandoah Valley Daily"),
        ("The Northern Virginia Daily", "nvdaily.com", "Strasburg", "Shenandoah Valley Daily"),
        ("The Winchester Star", "winchesterstar.com", "Winchester", "Daily"),
        ("The News Virginian", "newsvirginian.com", "Waynesboro", "Daily"),
        ("The Daily News Leader", "newsleader.com", "Staunton", "Daily"),
        ("The Progress-Index", "progress-index.com", "Petersburg", "Daily"),
        ("Suffolk News-Herald", "suffolknewsherald.com", "Suffolk", "Daily"),
        ("The Tidewater News", "thetidewaternews.com", "Franklin", "Semi-Weekly"),
        ("Martinsville Bulletin", "martinsvillebulletin.com", "Martinsville", "Daily"),
        ("Southwest Virginia Enterprise", "swvatoday.com", "Wytheville", "Semi-Weekly"),
        ("Inside Business", "pilotonline.com/inside-business", "Norfolk", "Weekly Business"),
        ("Fauquier Times", "fauquier.com", "Warrenton", "Weekly"),
        ("Loudoun Times-Mirror", "loudountimes.com", "Leesburg", "Weekly")
    ],
    "Washington": [
        ("The Seattle Times", "seattletimes.com", "Seattle", "Pacific Northwest Flagship Daily"),
        ("The News Tribune", "thenewstribune.com", "Tacoma", "South Sound Flagship Daily"),
        ("The Spokesman-Review", "spokesman.com", "Spokane", "Inland Northwest Flagship Daily"),
        ("The Columbian", "columbian.com", "Vancouver", "Clark County Flagship Daily"),
        ("The Herald", "heraldnet.com", "Everett", "Snohomish County Daily"),
        ("The Olympian", "theolympian.com", "Olympia", "State Capital Daily"),
        ("The Bellingham Herald", "bellinghamherald.com", "Bellingham", "Whatcom County Daily"),
        ("Tri-City Herald", "tri-cityherald.com", "Kennewick / Pasco / Richland", "Tri-Cities Daily"),
        ("Yakima Herald-Republic", "yakimaherald.com", "Yakima", "Central WA Daily"),
        ("The Wenatchee World", "wenatcheeworld.com", "Wenatchee", "North Central WA Daily"),
        ("Skagit Valley Herald", "goskagit.com", "Mount Vernon", "Daily"),
        ("The Daily World", "thedailyworld.com", "Aberdeen", "Grays Harbor Daily"),
        ("The Daily Chronicle", "chronline.com", "Centralia", "Lewis County Daily"),
        ("The Daily News", "tdn.com", "Longview", "Cowlitz County Daily"),
        ("Kitsap Sun", "kitsapsun.com", "Bremerton", "Kitsap Peninsula Daily"),
        ("Peninsula Daily News", "peninsuladailynews.com", "Port Angeles", "Olympic Peninsula Daily"),
        ("Walla Walla Union-Bulletin", "union-bulletin.com", "Walla Walla", "Daily"),
        ("Daily Record", "dailyrecordnews.com", "Ellensburg", "Daily"),
        ("The Daily Herald", "dailyastorian.com", "Ilwaco / Long Beach", "Weekly"),
        ("Whidbey News-Times", "whidbeynewstimes.com", "Oak Harbor", "Semi-Weekly"),
        ("The Stranger", "thestranger.com", "Seattle", "Alternative Bi-Weekly"),
        ("Seattle Weekly", "seattleweekly.com", "Seattle", "Weekly")
    ],
    "West Virginia": [
        ("The Charleston Gazette-Mail", "wvgazettemail.com", "Charleston", "Pulitzer Prize Winning Flagship"),
        ("The Herald-Dispatch", "herald-dispatch.com", "Huntington", "Top Daily"),
        ("The Dominion Post", "dominionpost.com", "Morgantown", "WVU Region Daily"),
        ("The Parkersburg News and Sentinel", "newsandsentinel.com", "Parkersburg", "Mid-Ohio Valley Daily"),
        ("The Intelligencer / Wheeling News-Register", "theintelligencer.net", "Wheeling", "Northern Panhandle Daily"),
        ("The Journal", "journal-news.net", "Martinsburg", "Eastern Panhandle Daily"),
        ("The Exponent Telegram", "theet.com", "Clarksburg", "North Central WV Daily"),
        ("The Register-Herald", "register-herald.com", "Beckley", "Southern WV Daily"),
        ("Bluefield Daily Telegraph", "bdtonline.com", "Bluefield", "Daily"),
        ("Times West Virginian", "timeswv.com", "Fairmont", "Daily"),
        ("The Inter-Mountain", "theintermountain.com", "Elkins", "Daily"),
        ("Mineral Daily News-Tribune", "newstribune.info", "Keyser", "Daily"),
        ("Weirton Daily Times", "weirtondailytimes.com", "Weirton", "Daily"),
        ("The Hampshire Review", "hampshirereview.com", "Romney", "Oldest WV Weekly"),
        ("The Morgan Messenger", "morganmessenger.com", "Berkeley Springs", "Weekly")
    ],
    "Wisconsin": [
        ("Milwaukee Journal Sentinel", "jsonline.com", "Milwaukee", "State Flagship Daily"),
        ("Wisconsin State Journal", "madison.com/wsj", "Madison", "State Capital Flagship Daily"),
        ("The Capital Times", "captimes.com", "Madison", "Madison Progressive Daily"),
        ("Green Bay Press-Gazette", "greenbaypressgazette.com", "Green Bay", "Packers Region Flagship"),
        ("The Post-Crescent", "postcrescent.com", "Appleton", "Fox Cities Flagship Daily"),
        ("The Northwestern", "thenorthwestern.com", "Oshkosh", "Winnebago County Daily"),
        ("The Sheboygan Press", "sheboyganpress.com", "Sheboygan", "Daily"),
        ("Herald Times Reporter", "htrnews.com", "Manitowoc", "Daily"),
        ("Kenosha News", "kenoshanews.com", "Kenosha", "Southeast WI Daily"),
        ("The Journal Times", "journaltimes.com", "Racine", "Southeast WI Daily"),
        ("La Crosse Tribune", "lacrossetribune.com", "La Crosse", "Coulee Region Daily"),
        ("Leader-Telegram", "leadertelegram.com", "Eau Claire", "Chippewa Valley Daily"),
        ("Wausau Daily Herald", "wausaudailyherald.com", "Wausau", "Central WI Daily"),
        ("Stevens Point Journal", "stevenspointjournal.com", "Stevens Point", "Daily"),
        ("Marshfield News-Herald", "marshfieldnewsherald.com", "Marshfield", "Daily"),
        ("Wisconsin Rapids Daily Tribune", "wisconsinrapidstribune.com", "Wisconsin Rapids", "Daily"),
        ("The Janesville Gazette", "gazettextra.com", "Janesville", "Rock County Daily"),
        ("Beloit Daily News", "beloitdailynews.com", "Beloit", "Daily"),
        ("The Freeman", "gmtoday.com/the_freeman", "Waukesha", "Daily"),
        ("Daily Citizen", "wiscnews.com/bdc", "Beaver Dam", "Daily"),
        ("Baraboo News Republic", "wiscnews.com/bnr", "Baraboo", "Daily"),
        ("Portage Daily Register", "wiscnews.com/pdr", "Portage", "Daily"),
        ("The Chippewa Herald", "chippewa.com", "Chippewa Falls", "Daily"),
        ("Superior Telegram", "superiortelegram.com", "Superior", "Daily"),
        ("The Daily News", "gmtoday.com/daily_news", "West Bend", "Daily"),
        ("Door County Pulse", "doorcountypulse.com", "Baileys Harbor / Door County", "Weekly")
    ],
    "Wyoming": [
        ("Casper Star-Tribune", "trib.com", "Casper", "State Flagship Daily"),
        ("Wyoming Tribune Eagle", "wyomingnews.com", "Cheyenne", "State Capital Flagship Daily"),
        ("Laramie Boomerang", "laramieboomerang.com", "Laramie", "University of Wyoming Daily"),
        ("Jackson Hole News&Guide", "jhnewsandguide.com", "Jackson Hole", "Teton County Weekly"),
        ("The Sheridan Press", "thesheridanpress.com", "Sheridan", "Northern WY Daily"),
        ("Gillette News Record", "gillettenewsrecord.com", "Gillette", "Energy Capital Daily"),
        ("Riverton Ranger", "rangerreview.com", "Riverton", "Fremont County"),
        ("The Rocket-Miner", "rocketminer.com", "Rock Springs", "Sweetwater County Daily"),
        ("The Cody Enterprise", "codyenterprise.com", "Cody", "Yellowstone Gateway"),
        ("Powell Tribune", "powelltribune.com", "Powell", "Semi-Weekly"),
        ("Rawlins Times", "rawlinstimes.com", "Rawlins", "Carbon County"),
        ("Torrington Telegram", "torringtontelegram.com", "Torrington", "Goshen County"),
        ("Buffalo Bulletin", "buffalobulletin.com", "Buffalo", "Weekly"),
        ("Platte County Record-Times", "pcrecordtimes.com", "Wheatland", "Weekly"),
        ("Douglas Budget", "douglas-budget.com", "Douglas", "Weekly")
    ]
}

# ==============================================================================
# STATE METADATA
# ==============================================================================
STATE_CODES = {
    "Alabama": "AL", "Alaska": "AK", "Arizona": "AZ", "Arkansas": "AR",
    "California": "CA", "Colorado": "CO", "Connecticut": "CT", "Delaware": "DE",
    "District of Columbia": "DC", "Florida": "FL", "Georgia": "GA", "Hawaii": "HI",
    "Idaho": "ID", "Illinois": "IL", "Indiana": "IN", "Iowa": "IA",
    "Kansas": "KS", "Kentucky": "KY", "Louisiana": "LA", "Maine": "ME",
    "Maryland": "MD", "Massachusetts": "MA", "Michigan": "MI", "Minnesota": "MN",
    "Mississippi": "MS", "Missouri": "MO", "Montana": "MT", "Nebraska": "NE",
    "Nevada": "NV", "New Hampshire": "NH", "New Jersey": "NJ", "New Mexico": "NM",
    "New York": "NY", "North Carolina": "NC", "North Dakota": "ND", "Ohio": "OH",
    "Oklahoma": "OK", "Oregon": "OR", "Pennsylvania": "PA", "Rhode Island": "RI",
    "South Carolina": "SC", "South Dakota": "SD", "Tennessee": "TN", "Texas": "TX",
    "Utah": "UT", "Vermont": "VT", "Virginia": "VA", "Washington": "WA",
    "West Virginia": "WV", "Wisconsin": "WI", "Wyoming": "WY"
}

REGION_MAP = {
    "Connecticut": "Northeast", "Maine": "Northeast", "Massachusetts": "Northeast",
    "New Hampshire": "Northeast", "Rhode Island": "Northeast", "Vermont": "Northeast",
    "New Jersey": "Mid-Atlantic", "New York": "Mid-Atlantic", "Pennsylvania": "Mid-Atlantic",
    "Illinois": "Midwest", "Indiana": "Midwest", "Michigan": "Midwest", "Ohio": "Midwest",
    "Wisconsin": "Midwest", "Iowa": "Midwest", "Kansas": "Midwest", "Minnesota": "Midwest",
    "Missouri": "Midwest", "Nebraska": "Midwest", "North Dakota": "Midwest", "South Dakota": "Midwest",
    "Delaware": "South", "Florida": "South", "Georgia": "South", "Maryland": "South",
    "North Carolina": "South", "South Carolina": "South", "Virginia": "South",
    "District of Columbia": "Capital Region", "West Virginia": "South", "Alabama": "South",
    "Kentucky": "South", "Mississippi": "South", "Tennessee": "South", "Arkansas": "South",
    "Louisiana": "South", "Oklahoma": "South", "Texas": "South",
    "Arizona": "Mountain West", "Colorado": "Mountain West", "Idaho": "Mountain West",
    "Montana": "Mountain West", "Nevada": "Mountain West", "New Mexico": "Mountain West",
    "Utah": "Mountain West", "Wyoming": "Mountain West",
    "Alaska": "Pacific", "California": "Pacific", "Hawaii": "Pacific",
    "Oregon": "Pacific", "Washington": "Pacific"
}

all_master_papers = []
state_category_menu = []

total_papers_count = sum(len(papers) for papers in RAW_STATE_PAPERS.values())

# Top item: All 50 States Master Feed
state_category_menu.append({
    "title": "🇺🇸 All 50 States (All Newspapers)",
    "provider": "overview",
    "arguments": ["states/all_states.json"],
    "image": "https://img.icons8.com/color/144/usa.png",
    "year": "50 States + DC",
    "genre": f"{total_papers_count} Newspapers",
    "rating": "All States"
})

sorted_states = sorted(RAW_STATE_PAPERS.keys())

for state_name in sorted_states:
    raw_list = RAW_STATE_PAPERS[state_name]
    formatted_papers = []
    
    for idx, paper in enumerate(raw_list):
        title, domain, city, rating = paper
        url = f"https://www.{domain}" if not domain.startswith("http") and not domain.startswith("al.com") else (domain if domain.startswith("http") else f"https://{domain}")
        formatted_papers.append({
            "title": title,
            "provider": "web",
            "arguments": [url],
            "image": favicon(domain.split('/')[0]),
            "year": state_name,
            "genre": city,
            "rating": rating
        })
        all_master_papers.append(formatted_papers[-1])
    
    slug = re.sub(r'[^a-zA-Z0-9]+', '_', state_name).strip('_').lower()
    state_filename = f"{slug}.json"
    state_filepath = os.path.join(states_dir, state_filename)
    
    with open(state_filepath, "w", encoding="utf-8") as sf:
        json.dump(formatted_papers, sf, indent=2, ensure_ascii=False)
    
    code = STATE_CODES.get(state_name, "US")
    region = REGION_MAP.get(state_name, "United States")
    count_str = f"{len(formatted_papers)} Newspaper" if len(formatted_papers) == 1 else f"{len(formatted_papers)} Newspapers"
    rep_image = formatted_papers[0].get("image") if formatted_papers else "https://img.icons8.com/color/96/newspaper.png"
    
    state_category_menu.append({
        "title": f"🏛️ {state_name}",
        "provider": "overview",
        "arguments": [f"states/{state_filename}"],
        "image": rep_image,
        "year": region,
        "genre": count_str,
        "rating": code
    })

# Save master all_states.json
all_states_path = os.path.join(states_dir, "all_states.json")
with open(all_states_path, "w", encoding="utf-8") as af:
    json.dump(all_master_papers, af, indent=2, ensure_ascii=False)

# Save usa_states_newspapers.json menu
menu_path = os.path.join(assets_dir, "usa_states_newspapers.json")
with open(menu_path, "w", encoding="utf-8") as mf:
    json.dump(state_category_menu, mf, indent=2, ensure_ascii=False)

print(f"[SUCCESS] Successfully built newspapers for {len(sorted_states)} States!")
print(f"[SUCCESS] Total Newspapers: {len(all_master_papers)}")
print(f"[SUCCESS] Master File: {all_states_path}")
print(f"[SUCCESS] Category Index: {menu_path}")
